/**
 * @file    unittest_grpc.cc
 * @date    28 Oct 2020
 * @brief   Unit test for gRPC tensor source/sink plugin
 * @see     https://github.com/nnstreamer/nnstreamer
 * @author  Dongju Chae <dongju.chae@samsung.com>
 * @bug     No known bugs
 */

#include <gtest/gtest.h>
#include <glib.h>
#include <gmodule.h>

#include <nnstreamer_conf.h>
#include <nnstreamer_plugin_api.h>
#include <nnstreamer_plugin_api_filter.h>

#include <functional>
#include <string>
#include <vector>

#if defined(ENABLE_PROTOBUF) || defined(ENABLE_FLATBUF)
#include <grpcpp/grpcpp.h>

#include "nnstreamer_grpc.h"
#include "tensor_sink_grpc.h"
#include "tensor_src_grpc.h"
#endif
#ifdef ENABLE_PROTOBUF
#include "nnstreamer.grpc.pb.h" /* Generated by `protoc` */
#endif
#ifdef ENABLE_FLATBUF
#include "nnstreamer.grpc.fb.h" /* Generated by `flatc` */
#endif

#define NNS_GRPC_PLUGIN_NAME "nnstreamer_grpc"
#define NNS_GRPC_TENSOR_SRC_NAME "tensor_src_grpc"
#define NNS_GRPC_TENSOR_SINK_NAME "tensor_sink_grpc"

/**
 * @brief Test gRPC tensor_src/sink existence.
 */
TEST (nnstreamerGrpc, checkExistence)
{
  GstPlugin *plugin;
  GstElementFactory *factory;

  plugin = gst_registry_find_plugin (gst_registry_get (), NNS_GRPC_PLUGIN_NAME);
  EXPECT_TRUE (plugin != NULL);
  gst_object_unref (plugin);

  factory = gst_element_factory_find (NNS_GRPC_TENSOR_SRC_NAME);
  EXPECT_TRUE (factory != NULL);
  gst_object_unref (factory);

  factory = gst_element_factory_find (NNS_GRPC_TENSOR_SINK_NAME);
  EXPECT_TRUE (factory != NULL);
  gst_object_unref (factory);
}

/**
 * @brief Test gRPC tensor_src/sink existence (negative).
 */
TEST (nnstreamerGrpc, checkExistence_n)
{
  GstPlugin *plugin;
  GstElementFactory *factory;
  gchar *name;

  name = g_strconcat (NNS_GRPC_PLUGIN_NAME, "_dummy", NULL);
  plugin = gst_registry_find_plugin (gst_registry_get (), name);
  EXPECT_TRUE (plugin == NULL);
  g_free (name);

  name = g_strconcat (NNS_GRPC_TENSOR_SRC_NAME, "_dummy", NULL);
  factory = gst_element_factory_find (name);
  EXPECT_TRUE (factory == NULL);
  g_free (name);

  name = g_strconcat (NNS_GRPC_TENSOR_SINK_NAME, "_dummy", NULL);
  factory = gst_element_factory_find (name);
  EXPECT_TRUE (factory == NULL);
  g_free (name);
}

/**
 * @brief Test modes.
 */
typedef enum { GRPC_MODE_BOTH = 0, GRPC_MODE_SRC, GRPC_MODE_SINK } TestMode;

/**
 * @brief Test options.
 */
typedef struct {
  gboolean server;
  gchar *host;
  guint port;
  guint fps;
  tensor_type type;
  TestMode mode;
} TestOption;

/**
 * @brief Data structure for test.
 */
typedef struct {
  GMainLoop *loop; /**< main event loop */
  GstElement *pipeline; /**< gst pipeline for test */
} TestData;

/**
 * @brief Data for pipeline and test result.
 */
static TestData test_data;

static gboolean DEFAULT_SERVER = TRUE;
static char DEFAULT_HOST[] = "localhost";
static guint DEFAULT_PORT = 55115;
static guint DEFAULT_FPS = 10;
static guint DEFAULT_OUT = 0;
static tensor_type DEFAULT_TYPE = _NNS_UINT8;

/**
 * @brief Prepare test pipeline
 */
static gboolean
_setup_pipeline (TestOption &option)
{
  gchar *str_pipeline;

  switch (option.mode) {
    case GRPC_MODE_SRC:
      str_pipeline = g_strdup_printf ("tensor_src_grpc name=src server=%s host=%s port=%u ! "
                                      "other/tensor,dimension=(string)1:1:1:1,type=(string)%s,framerate=(fraction)%u/1 ! "
                                      "fakesink",
          option.server ? "TRUE" : "FALSE", option.host, option.port,
          gst_tensor_get_type_string (option.type), option.fps);
      break;
    case GRPC_MODE_SINK:
      str_pipeline = g_strdup_printf (
          "videotestsrc ! video/x-raw,format=RGB,width=640,height=480,framerate=%u/1 !"
          "tensor_converter ! tensor_sink_grpc name=sink server=%s host=%s port=%u",
          option.fps, option.server ? "TRUE" : "FALSE", option.host, option.port);
      break;
    default:
      return FALSE;
  }

  test_data.pipeline = gst_parse_launch (str_pipeline, NULL);
  g_free (str_pipeline);

  return test_data.pipeline != NULL ? TRUE : FALSE;
}

/**
 * @brief set default option
 */
static void
_set_default_option (TestOption &option)
{
  option.server = DEFAULT_SERVER;
  option.host = DEFAULT_HOST;
  option.port = DEFAULT_PORT;
  option.fps = DEFAULT_FPS;
  option.type = DEFAULT_TYPE;
  option.mode = GRPC_MODE_BOTH;
}

/**
 * @brief Test gRPC tensor_src get default property
 */
TEST (nnstreamerGrpc, srcGetPropertyDefault)
{
  TestOption option;
  GstElement *src;
  gboolean silent, server;
  guint port, out;
  gchar *host;

  _set_default_option (option);
  option.mode = GRPC_MODE_SRC;

  ASSERT_TRUE (_setup_pipeline (option));

  src = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "src");
  ASSERT_TRUE (src != NULL);

  g_object_get (src, "silent", &silent, NULL);
  EXPECT_TRUE (silent);

  g_object_get (src, "server", &server, NULL);
  EXPECT_EQ (server, DEFAULT_SERVER);

  g_object_get (src, "host", &host, NULL);
  EXPECT_STREQ (host, DEFAULT_HOST);
  g_free (host);

  g_object_get (src, "port", &port, NULL);
  EXPECT_EQ (port, DEFAULT_PORT);

  g_object_get (src, "out", &out, NULL);
  EXPECT_EQ (out, DEFAULT_OUT);

  gst_object_unref (src);
  gst_object_unref (test_data.pipeline);
}

/**
 * @brief Test gRPC tensor_sink get default property
 */
TEST (nnstreamerGrpc, sinkGetPropertyDefault)
{
  TestOption option;
  GstElement *sink;
  gboolean silent, server;
  guint port, out;
  gchar *host;

  _set_default_option (option);
  option.mode = GRPC_MODE_SINK;

  ASSERT_TRUE (_setup_pipeline (option));

  sink = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "sink");
  ASSERT_TRUE (sink != NULL);

  g_object_get (sink, "silent", &silent, NULL);
  EXPECT_TRUE (silent);

  g_object_get (sink, "server", &server, NULL);
  EXPECT_EQ (server, DEFAULT_SERVER);

  g_object_get (sink, "host", &host, NULL);
  EXPECT_STREQ (host, DEFAULT_HOST);
  g_free (host);

  g_object_get (sink, "port", &port, NULL);
  EXPECT_EQ (port, DEFAULT_PORT);

  g_object_get (sink, "out", &out, NULL);
  EXPECT_EQ (out, DEFAULT_OUT);

  gst_object_unref (sink);
  gst_object_unref (test_data.pipeline);
}

/**
 * @brief Test gRPC tensor_src set property
 */
TEST (nnstreamerGrpc, srcSetProperty)
{
  TestOption option;
  GstElement *src;
  gboolean silent, server;
  guint port;
  gchar *host;

  _set_default_option (option);
  option.mode = GRPC_MODE_SRC;

  ASSERT_TRUE (_setup_pipeline (option));

  src = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "src");
  ASSERT_TRUE (src != NULL);

  g_object_set (src, "silent", (gboolean) FALSE, NULL);
  g_object_get (src, "silent", &silent, NULL);
  EXPECT_TRUE (!silent);

  g_object_set (src, "server", (gboolean) FALSE, NULL);
  g_object_get (src, "server", &server, NULL);
  EXPECT_TRUE (!server);

  g_object_set (src, "host", "1.1.1.1", NULL);
  g_object_get (src, "host", &host, NULL);
  EXPECT_STREQ (host, "1.1.1.1");
  g_free (host);

  g_object_set (src, "port", 1000, NULL);
  g_object_get (src, "port", &port, NULL);
  EXPECT_EQ (port, 1000U);

  gst_object_unref (src);
  gst_object_unref (test_data.pipeline);
}

/**
 * @brief Test gRPC tensor_sink set property
 */
TEST (nnstreamerGrpc, sinkSetProperty)
{
  TestOption option;
  GstElement *sink;
  gboolean silent, server;
  guint port;
  gchar *host;

  _set_default_option (option);
  option.mode = GRPC_MODE_SINK;

  ASSERT_TRUE (_setup_pipeline (option));

  sink = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "sink");
  ASSERT_TRUE (sink != NULL);

  g_object_set (sink, "silent", (gboolean) FALSE, NULL);
  g_object_get (sink, "silent", &silent, NULL);
  EXPECT_TRUE (!silent);

  g_object_set (sink, "server", (gboolean) FALSE, NULL);
  g_object_get (sink, "server", &server, NULL);
  EXPECT_TRUE (!server);

  g_object_set (sink, "host", "1.1.1.1", NULL);
  g_object_get (sink, "host", &host, NULL);
  EXPECT_STREQ (host, "1.1.1.1");
  g_free (host);

  g_object_set (sink, "port", 1000, NULL);
  g_object_get (sink, "port", &port, NULL);
  EXPECT_EQ (port, 1000U);

  gst_object_unref (sink);
  gst_object_unref (test_data.pipeline);
}

/**
 * @brief Test gRPC tensor_src invalid host
 */
TEST (nnstreamerGrpc, srcInvalidHost_n)
{
  TestOption option;
  GstElement *src;
  gchar *host;

  _set_default_option (option);
  option.mode = GRPC_MODE_SRC;

  ASSERT_TRUE (_setup_pipeline (option));

  src = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "src");
  ASSERT_TRUE (src != NULL);

  g_object_set (src, "host", "invalid host", NULL);
  g_object_get (src, "host", &host, NULL);
  EXPECT_STREQ (host, DEFAULT_HOST);
  g_free (host);

  gst_object_unref (src);
  gst_object_unref (test_data.pipeline);
}

/**
 * @brief Test gRPC tensor_sink invalid host
 */
TEST (nnstreamerGrpc, sinkInvalidHost_n)
{
  TestOption option;
  GstElement *sink;
  gchar *host;

  _set_default_option (option);
  option.mode = GRPC_MODE_SINK;

  ASSERT_TRUE (_setup_pipeline (option));

  sink = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "sink");
  ASSERT_TRUE (sink != NULL);

  g_object_set (sink, "host", "invalid host", NULL);
  g_object_get (sink, "host", &host, NULL);
  EXPECT_STREQ (host, DEFAULT_HOST);
  g_free (host);

  gst_object_unref (sink);
  gst_object_unref (test_data.pipeline);
}

/**
 * @brief Test gRPC tensor_src invalid port
 */
TEST (nnstreamerGrpc, srcInvalidPort_n)
{
  TestOption option;
  GstElement *src;
  guint port;

  _set_default_option (option);
  option.mode = GRPC_MODE_SRC;

  ASSERT_TRUE (_setup_pipeline (option));

  src = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "src");
  ASSERT_TRUE (src != NULL);

  g_object_set (src, "port", G_MAXUSHORT + 1, NULL);
  g_object_get (src, "port", &port, NULL);
  EXPECT_EQ (port, DEFAULT_PORT);

  g_object_set (src, "port", "5555", NULL);
  g_object_get (src, "port", &port, NULL);
  EXPECT_EQ (port, DEFAULT_PORT);

  gst_object_unref (src);
  gst_object_unref (test_data.pipeline);
}

/**
 * @brief Test gRPC tensor_sink invalid port
 */
TEST (nnstreamerGrpc, sinkInvalidPort_n)
{
  TestOption option;
  GstElement *sink;
  guint port;

  _set_default_option (option);
  option.mode = GRPC_MODE_SINK;

  ASSERT_TRUE (_setup_pipeline (option));

  sink = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "sink");
  ASSERT_TRUE (sink != NULL);

  g_object_set (sink, "port", G_MAXUSHORT + 1, NULL);
  g_object_get (sink, "port", &port, NULL);
  EXPECT_EQ (port, DEFAULT_PORT);

  g_object_set (sink, "port", "5555", NULL);
  g_object_get (sink, "port", &port, NULL);
  EXPECT_EQ (port, DEFAULT_PORT);

  gst_object_unref (sink);
  gst_object_unref (test_data.pipeline);
}

#if defined(ENABLE_PROTOBUF) || defined(ENABLE_FLATBUF)
/**
 * @brief Address of the TEST-NET-1 block; no local interface can bind to it.
 */
#define UNBINDABLE_HOST "192.0.2.1"

/**
 * @brief Caps of the pipelines that stream one uint8 tensor of a 16x16 RGB frame.
 */
#define STREAM_VIDEO_CAPS \
  "video/x-raw,format=RGB,width=16,height=16,framerate=30/1"
#define STREAM_TENSOR_CAPS \
  "other/tensor,dimension=3:16:16,type=uint8,framerate=30/1"

/**
 * @brief Get the gRPC instance tensor_src_grpc holds, NULL if it holds none.
 */
static void *
_src_grpc_instance (GstElement *element)
{
  return ((grpc_private *) ((GstTensorSrcGRPC *) element)->priv)->instance;
}

/**
 * @brief Get the gRPC instance tensor_sink_grpc holds, NULL if it holds none.
 */
static void *
_sink_grpc_instance (GstElement *element)
{
  return ((grpc_private *) ((GstTensorSinkGRPC *) element)->priv)->instance;
}

/**
 * @brief Build a gRPC element and bring it to PAUSED, where start () has run.
 * @return the state change result; the element is returned in @a element
 */
static GstStateChangeReturn
_start_grpc_element (const gchar *name, const gchar *host, GstElement **element)
{
  GstElement *e = gst_element_factory_make (name, NULL);

  if (!e)
    return GST_STATE_CHANGE_FAILURE;

  g_object_set (e, "server", (gboolean) TRUE, "host", host, "port", 0, NULL);
  *element = e;

  return gst_element_set_state (e, GST_STATE_PAUSED);
}

/**
 * @brief Wait until the source pad of @a element has negotiated its caps.
 */
static gboolean
_wait_for_caps (GstElement *element)
{
  GstPad *pad = gst_element_get_static_pad (element, "src");
  GstCaps *caps = NULL;
  guint i;

  for (i = 0; i < 1000 && !caps; i++) {
    caps = gst_pad_get_current_caps (pad);
    if (!caps)
      g_usleep (10000);
  }
  gst_object_unref (pad);

  if (!caps)
    return FALSE;

  gst_caps_unref (caps);
  return TRUE;
}

/**
 * @brief The element flags must not alias any flag of their base class.
 *
 * Every bit a base class may take is below the FLAG_LAST it declares; GstBaseSink
 * declares none of its own, so GstElement's is the bound of the sink.
 */
TEST (nnstreamerGrpc, elementFlags)
{
  guint src_base = (guint) GST_BASE_SRC_FLAG_LAST - 1;
  guint sink_base = (guint) GST_ELEMENT_FLAG_LAST - 1;

  EXPECT_EQ ((guint) GST_TENSOR_SRC_GRPC_CONFIGURED & src_base, 0U);
  EXPECT_EQ ((guint) GST_TENSOR_SRC_GRPC_STARTED & src_base, 0U);
  EXPECT_EQ ((guint) GST_TENSOR_SINK_GRPC_CONFIGURED & sink_base, 0U);
  EXPECT_EQ ((guint) GST_TENSOR_SINK_GRPC_STARTED & sink_base, 0U);
}

/**
 * @brief tensor_src_grpc releases its gRPC instance when the element stops.
 */
TEST (nnstreamerGrpc, srcReleasesInstance)
{
  GstElement *src = NULL;

  ASSERT_NE (_start_grpc_element ("tensor_src_grpc", "localhost", &src), GST_STATE_CHANGE_FAILURE);
  EXPECT_TRUE (_src_grpc_instance (src) != NULL);

  gst_element_set_state (src, GST_STATE_NULL);
  EXPECT_TRUE (_src_grpc_instance (src) == NULL);

  gst_object_unref (src);
}

/**
 * @brief tensor_sink_grpc releases its gRPC instance when the element stops.
 */
TEST (nnstreamerGrpc, sinkReleasesInstance)
{
  GstElement *sink = NULL;

  ASSERT_NE (_start_grpc_element ("tensor_sink_grpc", "localhost", &sink),
      GST_STATE_CHANGE_FAILURE);
  EXPECT_TRUE (_sink_grpc_instance (sink) != NULL);

  gst_element_set_state (sink, GST_STATE_NULL);
  EXPECT_TRUE (_sink_grpc_instance (sink) == NULL);

  gst_object_unref (sink);
}

/**
 * @brief tensor_src_grpc fails to start and holds no instance when its server cannot listen.
 */
TEST (nnstreamerGrpc, srcStartFailure_n)
{
  GstElement *src = NULL;

  EXPECT_EQ (_start_grpc_element ("tensor_src_grpc", UNBINDABLE_HOST, &src),
      GST_STATE_CHANGE_FAILURE);
  ASSERT_TRUE (src != NULL);
  EXPECT_TRUE (_src_grpc_instance (src) == NULL);

  gst_element_set_state (src, GST_STATE_NULL);
  gst_object_unref (src);
}

/**
 * @brief tensor_sink_grpc fails to start and holds no instance when its server cannot listen.
 */
TEST (nnstreamerGrpc, sinkStartFailure_n)
{
  GstElement *sink = NULL;

  EXPECT_EQ (_start_grpc_element ("tensor_sink_grpc", UNBINDABLE_HOST, &sink),
      GST_STATE_CHANGE_FAILURE);
  ASSERT_TRUE (sink != NULL);
  EXPECT_TRUE (_sink_grpc_instance (sink) == NULL);

  gst_element_set_state (sink, GST_STATE_NULL);
  gst_object_unref (sink);
}

/**
 * @brief Static caps of the received-message tests: two uint8 tensors of 4 and 2 bytes.
 */
#define RECV_STATIC_CAPS \
  "other/tensors,num_tensors=2,dimensions=4:1:1:1.2:1:1:1,types=uint8.uint8,framerate=30/1"

/**
 * @brief Buffers tensor_sink got from tensor_src_grpc.
 */
typedef struct {
  GMutex lock; /**< protects the fields below */
  guint received; /**< number of buffers */
  std::vector<gsize> sizes; /**< memory sizes of the last buffer */
} RecvData;

/**
 * @brief tensor_sink new-data callback, records the memory sizes of the buffer.
 */
static void
_recv_new_data_cb (GstElement *element, GstBuffer *buffer, gpointer user_data)
{
  RecvData *data = (RecvData *) user_data;
  guint i, num;

  g_mutex_lock (&data->lock);
  data->received++;
  data->sizes.clear ();
  num = gst_tensor_buffer_get_count (buffer);
  for (i = 0; i < num; i++) {
    GstMemory *mem = gst_tensor_buffer_get_nth_memory (buffer, i);
    data->sizes.push_back (gst_memory_get_sizes (mem, NULL, NULL));
    gst_memory_unref (mem);
  }
  g_mutex_unlock (&data->lock);
}

/**
 * @brief Sends messages to the given address; calls the given function to wait for the buffers before closing the call.
 */
typedef std::function<void (const std::string &, const std::function<void ()> &)> RecvSendFunc;

/**
 * @brief Run tensor_src_grpc as a server, let @a send stream messages to it, and wait for @a expected buffers.
 * @return the number of buffers tensor_sink received (G_MAXUINT if the server did not start), the memory sizes of the last one in @a sizes.
 */
static guint
_run_recv_test (const gchar *idl, const std::string &caps,
    const RecvSendFunc &send, guint expected, std::vector<gsize> &sizes)
{
  GstElement *pipeline, *src, *sink;
  GstPad *pad;
  GstCaps *current = NULL;
  RecvData data;
  gchar *str;
  gint port = 0;
  guint i, received;

  str = g_strdup_printf ("tensor_src_grpc name=src server=TRUE blocking=TRUE idl=%s host=localhost port=0 ! %s ! "
                         "tensor_sink name=sink emit-signal=TRUE sync=FALSE async=FALSE",
      idl, caps.c_str ());
  pipeline = gst_parse_launch (str, NULL);
  g_free (str);
  if (!pipeline)
    return G_MAXUINT;

  g_mutex_init (&data.lock);
  data.received = 0;

  src = gst_bin_get_by_name (GST_BIN (pipeline), "src");
  sink = gst_bin_get_by_name (GST_BIN (pipeline), "sink");
  g_signal_connect (sink, "new-data", G_CALLBACK (_recv_new_data_cb), &data);

  gst_element_set_state (pipeline, GST_STATE_PLAYING);

  /* the server has started and the caps are set once the pad has them */
  pad = gst_element_get_static_pad (src, "src");
  for (i = 0; i < 1000 && !current; i++) {
    current = gst_pad_get_current_caps (pad);
    if (!current)
      g_usleep (10000);
  }
  gst_object_unref (pad);

  if (current) {
    gst_caps_unref (current);
    g_object_get (src, "port", &port, NULL);
    send ("localhost:" + std::to_string (port), [&] () {
      for (i = 0; i < 1000; i++) {
        g_mutex_lock (&data.lock);
        received = data.received;
        g_mutex_unlock (&data.lock);
        if (received >= expected)
          break;
        g_usleep (10000);
      }
    });
  }

  gst_element_set_state (pipeline, GST_STATE_NULL);

  received = data.received;
  sizes = data.sizes;

  gst_object_unref (src);
  gst_object_unref (sink);
  gst_object_unref (pipeline);
  g_mutex_clear (&data.lock);

  return current ? received : G_MAXUINT;
}

/**
 * @brief Wait until @a data has @a expected buffers, at most 10 seconds.
 */
static guint
_wait_for_buffers (RecvData &data, guint expected)
{
  guint i, received = 0;

  for (i = 0; i < 1000; i++) {
    g_mutex_lock (&data.lock);
    received = data.received;
    g_mutex_unlock (&data.lock);
    if (received >= expected)
      break;
    g_usleep (10000);
  }

  return received;
}

/**
 * @brief Reader of the client-call counters a gRPC sub-plugin exports.
 */
typedef void (*grpc_call_stats_fn) (gint *live, gint *unfinished);

/**
 * @brief Open the sub-plugin of @a idl and keep it loaded while a test runs.
 * @param[out] stats its counter reader, NULL if the sub-plugin exports none
 * @return the module, NULL if it cannot be opened
 *
 * The element closes its own handle when it releases the instance, which
 * unloads the sub-plugin and resets the counters; the caller has to hold a
 * handle of its own across the run to read them afterwards.
 */
static GModule *
_open_grpc_idl_module (const gchar *idl, grpc_call_stats_fn *stats)
{
  gchar *name = g_strdup_printf ("libnnstreamer_grpc_%s%s", idl, NNSTREAMER_SO_FILE_EXTENSION);
  GModule *module = g_module_open (name, G_MODULE_BIND_LAZY);

  *stats = NULL;
  if (module && !g_module_symbol (module, "nnstreamer_grpc_get_client_call_stats", (gpointer *) stats))
    *stats = NULL;

  g_free (name);

  return module;
}

/**
 * @brief Wait until no buffer has arrived for 200 ms, at most 2 seconds.
 */
static void
_wait_for_stream_end (RecvData &data)
{
  guint i, now, last = 0, stable = 0;

  for (i = 0; i < 100 && stable < 10; i++) {
    g_usleep (20000);
    g_mutex_lock (&data.lock);
    now = data.received;
    g_mutex_unlock (&data.lock);
    stable = (now == last) ? stable + 1 : 0;
    last = now;
  }
}

/**
 * @brief Stream tensors between a blocking server and a non-blocking (async) client.
 * @param idl the IDL both ends use
 * @param client_src TRUE to let tensor_src_grpc be the client, FALSE to let tensor_sink_grpc be it
 * @return the number of buffers tensor_sink got, 0 if a pipeline did not build or start
 *
 * The peer of the client is torn down first, so that the client handles the
 * end of the stream while its completion queue still has a batch outstanding.
 * Every client call of the run has to be gone by the end of it, and none of
 * them may have been freed while its completion queue still held a batch.
 */
static guint
_run_nonblocking_test (const gchar *idl, gboolean client_src)
{
  GstElement *server, *client, *grpc, *sink = NULL;
  grpc_call_stats_fn stats;
  GModule *module;
  RecvData data;
  gchar *str;
  gint port = 0;
  gint live_before = 0, unfinished_before = 0, live = 0, unfinished = 0;
  guint received;

  if (client_src)
    str = g_strdup_printf ("videotestsrc num-buffers=10 ! " STREAM_VIDEO_CAPS " ! tensor_converter ! "
                           "tensor_sink_grpc name=grpc server=TRUE blocking=TRUE idl=%s "
                           "host=localhost port=0 async=FALSE",
        idl);
  else
    str = g_strdup_printf ("tensor_src_grpc name=grpc server=TRUE blocking=TRUE idl=%s "
                           "host=localhost port=0 ! " STREAM_TENSOR_CAPS
                           " ! tensor_sink name=sink emit-signal=TRUE sync=FALSE async=FALSE",
        idl);
  server = gst_parse_launch (str, NULL);
  g_free (str);
  if (!server) {
    ADD_FAILURE () << "the server pipeline of the " << idl << " test did not build";
    return 0;
  }

  module = _open_grpc_idl_module (idl, &stats);
  EXPECT_TRUE (module != NULL);
  EXPECT_TRUE (stats != NULL);
  if (stats)
    stats (&live_before, &unfinished_before);

  g_mutex_init (&data.lock);
  data.received = 0;

  grpc = gst_bin_get_by_name (GST_BIN (server), "grpc");
  gst_element_set_state (server, GST_STATE_PLAYING);

  if (client_src)
    gst_element_get_state (server, NULL, NULL, 10 * GST_SECOND);
  else if (_wait_for_caps (grpc)) {
    sink = gst_bin_get_by_name (GST_BIN (server), "sink");
    g_signal_connect (sink, "new-data", G_CALLBACK (_recv_new_data_cb), &data);
    gst_object_unref (sink);
  }

  g_object_get (grpc, "port", &port, NULL);
  gst_object_unref (grpc);

  /* the server did not start; nothing has been queued for it either */
  if (port <= 0) {
    ADD_FAILURE () << "the " << idl << " server did not get a port to listen on";
    gst_element_set_state (server, GST_STATE_NULL);
    gst_object_unref (server);
    g_mutex_clear (&data.lock);
    if (module)
      g_module_close (module);
    return 0;
  }

  if (client_src)
    str = g_strdup_printf (
        "tensor_src_grpc server=FALSE blocking=FALSE idl=%s host=localhost port=%d ! " STREAM_TENSOR_CAPS
        " ! tensor_sink name=sink emit-signal=TRUE sync=FALSE async=FALSE",
        idl, port);
  else
    str = g_strdup_printf (
        "videotestsrc num-buffers=10 ! " STREAM_VIDEO_CAPS " ! tensor_converter ! "
        "tensor_sink_grpc server=FALSE blocking=FALSE idl=%s host=localhost port=%d",
        idl, port);
  client = gst_parse_launch (str, NULL);
  g_free (str);
  if (!client)
    ADD_FAILURE () << "the client pipeline of the " << idl << " test did not build";

  if (client) {
    if (client_src) {
      sink = gst_bin_get_by_name (GST_BIN (client), "sink");
      g_signal_connect (sink, "new-data", G_CALLBACK (_recv_new_data_cb), &data);
      gst_object_unref (sink);
    }
    gst_element_set_state (client, GST_STATE_PLAYING);
  }

  received = _wait_for_buffers (data, 2);

  /* the peer leaves first; the client has to finish its call on its own */
  if (client_src) {
    gst_element_set_state (server, GST_STATE_NULL);
    _wait_for_stream_end (data);
    if (client)
      gst_element_set_state (client, GST_STATE_NULL);
  } else {
    if (client)
      gst_element_set_state (client, GST_STATE_NULL);
    gst_element_set_state (server, GST_STATE_NULL);
  }

  /* the elements have joined their worker threads by now */
  if (stats) {
    stats (&live, &unfinished);
    EXPECT_EQ (live, live_before);
    EXPECT_EQ (unfinished, unfinished_before);
  }

  if (client)
    gst_object_unref (client);
  gst_object_unref (server);
  g_mutex_clear (&data.lock);
  if (module)
    g_module_close (module);

  return client ? received : 0;
}

#endif /* ENABLE_PROTOBUF || ENABLE_FLATBUF */

#ifdef ENABLE_PROTOBUF
using PbTensors = nnstreamer::protobuf::Tensors;

/**
 * @brief Add a uint8 tensor holding @a data to a protobuf message.
 */
static void
_pb_add_tensor (PbTensors &msg, const std::string &data)
{
  nnstreamer::protobuf::Tensor *tensor = msg.add_tensor ();

  tensor->set_name ("test");
  tensor->set_type (nnstreamer::protobuf::Tensor::NNS_UINT8);
  tensor->add_dimension (data.size ());
  tensor->set_data (data);
}

/**
 * @brief Build a protobuf message that fits RECV_STATIC_CAPS.
 */
static PbTensors
_pb_valid_static (void)
{
  PbTensors msg;

  msg.set_num_tensor (2);
  _pb_add_tensor (msg, std::string (4, '\x01'));
  _pb_add_tensor (msg, std::string (2, '\x02'));
  return msg;
}

/**
 * @brief Send @a msgs over one client-streaming call of the protobuf service.
 */
static void
_pb_send (const std::string &address, const std::function<void ()> &wait,
    const std::vector<PbTensors> &msgs)
{
  auto stub = nnstreamer::protobuf::TensorService::NewStub (
      grpc::CreateChannel (address, grpc::InsecureChannelCredentials ()));
  grpc::ClientContext context;
  google::protobuf::Empty reply;
  auto writer = stub->SendTensors (&context, &reply);

  for (const PbTensors &msg : msgs)
    writer->Write (msg);
  writer->WritesDone ();
  wait ();
  writer->Finish ();
}

/**
 * @brief Run a protobuf receive test on @a caps: @a msgs, then wait for one buffer.
 */
static guint
_pb_recv (const std::string &caps, const std::vector<PbTensors> &msgs,
    std::vector<gsize> &sizes)
{
  return _run_recv_test (
      "protobuf", caps,
      [&] (const std::string &addr, const std::function<void ()> &wait) {
        _pb_send (addr, wait, msgs);
      },
      1, sizes);
}

/**
 * @brief tensor_src_grpc (protobuf) delivers a message that fits the caps.
 */
TEST (nnstreamerGrpc, recvProtobufStatic)
{
  std::vector<gsize> sizes;
  guint received = _pb_recv (RECV_STATIC_CAPS, { _pb_valid_static () }, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
  EXPECT_EQ (sizes[0], 4U);
  EXPECT_EQ (sizes[1], 2U);
}

/**
 * @brief tensor_src_grpc (protobuf) drops a message declaring more tensors than it carries.
 */
TEST (nnstreamerGrpc, recvProtobufMissingTensor_n)
{
  std::vector<gsize> sizes;
  PbTensors bad;

  bad.set_num_tensor (2);
  _pb_add_tensor (bad, std::string (4, '\x01'));

  guint received = _pb_recv (RECV_STATIC_CAPS, { bad, _pb_valid_static () }, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
}

/**
 * @brief tensor_src_grpc (protobuf) drops a message whose tensor count differs from the caps.
 */
TEST (nnstreamerGrpc, recvProtobufCountMismatch_n)
{
  std::vector<gsize> sizes;
  PbTensors bad;

  bad.set_num_tensor (1);
  _pb_add_tensor (bad, std::string (4, '\x01'));

  guint received = _pb_recv (RECV_STATIC_CAPS, { bad, _pb_valid_static () }, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
}

/**
 * @brief tensor_src_grpc (protobuf) drops a message whose data size differs from the caps.
 */
TEST (nnstreamerGrpc, recvProtobufSizeMismatch_n)
{
  std::vector<gsize> sizes;
  PbTensors bad;

  bad.set_num_tensor (2);
  _pb_add_tensor (bad, std::string (4, '\x01'));
  _pb_add_tensor (bad, std::string (3, '\x02'));

  guint received = _pb_recv (RECV_STATIC_CAPS, { bad, _pb_valid_static () }, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
  EXPECT_EQ (sizes[1], 2U);
}

/**
 * @brief Static caps of @a num one-byte uint8 tensors.
 */
static std::string
_many_tensors_caps (guint num)
{
  std::string dims, types;

  for (guint i = 0; i < num; i++) {
    dims += (i ? "." : "") + std::string ("1:1:1:1");
    types += (i ? "." : "") + std::string ("uint8");
  }

  return "other/tensors,num_tensors=" + std::to_string (num)
         + ",dimensions=" + dims + ",types=" + types + ",framerate=30/1";
}

/**
 * @brief Build a protobuf message of @a num one-byte tensors; tensor @a wrong gets two bytes.
 */
static PbTensors
_pb_many_tensors (guint num, guint wrong)
{
  PbTensors msg;

  msg.set_num_tensor (num);
  for (guint i = 0; i < num; i++)
    _pb_add_tensor (msg, std::string (i == wrong ? 2 : 1, '\x01'));
  return msg;
}

/**
 * @brief tensor_src_grpc (protobuf) delivers a message with more tensors than a buffer has memories.
 */
TEST (nnstreamerGrpc, recvProtobufExtraTensors)
{
  std::vector<gsize> sizes;
  guint received = _pb_recv (_many_tensors_caps (NNS_TENSOR_MEMORY_MAX + 4),
      { _pb_many_tensors (NNS_TENSOR_MEMORY_MAX + 4, G_MAXUINT) }, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), NNS_TENSOR_MEMORY_MAX + 4U);
  EXPECT_EQ (sizes[NNS_TENSOR_MEMORY_MAX + 3], 1U);
}

/**
 * @brief tensor_src_grpc (protobuf) drops a message whose extra tensor has the wrong size.
 */
TEST (nnstreamerGrpc, recvProtobufExtraTensorSizeMismatch_n)
{
  std::vector<gsize> sizes;
  guint received = _pb_recv (_many_tensors_caps (NNS_TENSOR_MEMORY_MAX + 4),
      { _pb_many_tensors (NNS_TENSOR_MEMORY_MAX + 4, NNS_TENSOR_MEMORY_MAX + 2),
          _pb_many_tensors (NNS_TENSOR_MEMORY_MAX + 4, G_MAXUINT) },
      sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), NNS_TENSOR_MEMORY_MAX + 4U);
  EXPECT_EQ (sizes[NNS_TENSOR_MEMORY_MAX + 2], 1U);
}

/**
 * @brief A non-blocking tensor_src_grpc (protobuf) client receives tensors and ends its call.
 */
TEST (nnstreamerGrpc, nonBlockingClientSrcProtobuf)
{
  EXPECT_GE (_run_nonblocking_test ("protobuf", TRUE), 2U);
}

/**
 * @brief A non-blocking tensor_sink_grpc (protobuf) client sends tensors and ends its call.
 */
TEST (nnstreamerGrpc, nonBlockingClientSinkProtobuf)
{
  EXPECT_GE (_run_nonblocking_test ("protobuf", FALSE), 2U);
}
#endif /* ENABLE_PROTOBUF */

#ifdef ENABLE_FLATBUF
using FbTensors = nnstreamer::flatbuf::Tensors;
using FbMessage = flatbuffers::grpc::Message<FbTensors>;

/**
 * @brief Build a flatbuf message with uint8 tensors of @a data_sizes bytes.
 * @param data_sizes A negative size leaves the data field of that tensor out; NULL leaves the tensor vector out.
 */
static FbMessage
_fb_build (gint num_tensor, const std::vector<gint> *data_sizes)
{
  flatbuffers::grpc::MessageBuilder builder;
  std::vector<flatbuffers::Offset<nnstreamer::flatbuf::Tensor>> tensors;
  nnstreamer::flatbuf::frame_rate fr (30, 1);
  guint32 dim[NNS_TENSOR_RANK_LIMIT] = { 0 };
  flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<nnstreamer::flatbuf::Tensor>>> vec;

  if (data_sizes) {
    for (gint size : *data_sizes) {
      std::vector<guint8> bytes (size > 0 ? size : 0, 1);
      auto name = builder.CreateString ("test");
      auto dims = builder.CreateVector (dim, NNS_TENSOR_RANK_LIMIT);
      flatbuffers::Offset<flatbuffers::Vector<guint8>> data;

      if (size >= 0)
        data = builder.CreateVector (bytes);

      tensors.push_back (nnstreamer::flatbuf::CreateTensor (builder, name,
          nnstreamer::flatbuf::Tensor_type_NNS_UINT8, dims, data));
    }
    vec = builder.CreateVector (tensors);
  }

  builder.Finish (nnstreamer::flatbuf::CreateTensors (builder, num_tensor, &fr, vec));
  return builder.ReleaseMessage<FbTensors> ();
}

/**
 * @brief Send @a msgs over one client-streaming call of the flatbuf service.
 */
static void
_fb_send (const std::string &address, const std::function<void ()> &wait,
    std::vector<FbMessage> &msgs)
{
  auto stub = nnstreamer::flatbuf::TensorService::NewStub (
      grpc::CreateChannel (address, grpc::InsecureChannelCredentials ()));
  grpc::ClientContext context;
  flatbuffers::grpc::Message<nnstreamer::flatbuf::Empty> reply;
  auto writer = stub->SendTensors (&context, &reply);

  for (FbMessage &msg : msgs)
    writer->Write (msg);
  writer->WritesDone ();
  /* Finish () of a flatbuf client-streaming call aborts, see SyncServiceImplFlatbuf::_client_thread (). */
  wait ();
}

/**
 * @brief Run a flatbuf receive test on RECV_STATIC_CAPS: the given message (if @a with_bad), then a valid one.
 */
static guint
_fb_recv (gboolean with_bad, gint num_tensor,
    const std::vector<gint> *data_sizes, std::vector<gsize> &sizes)
{
  const std::vector<gint> valid = { 4, 2 };

  return _run_recv_test (
      "flatbuf", RECV_STATIC_CAPS,
      [&] (const std::string &addr, const std::function<void ()> &wait) {
        std::vector<FbMessage> msgs;
        if (with_bad)
          msgs.push_back (_fb_build (num_tensor, data_sizes));
        msgs.push_back (_fb_build (2, &valid));
        _fb_send (addr, wait, msgs);
      },
      1, sizes);
}

/**
 * @brief tensor_src_grpc (flatbuf) delivers a message that fits the caps.
 */
TEST (nnstreamerGrpc, recvFlatbufStatic)
{
  std::vector<gsize> sizes;
  guint received = _fb_recv (FALSE, 0, NULL, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
  EXPECT_EQ (sizes[0], 4U);
  EXPECT_EQ (sizes[1], 2U);
}

/**
 * @brief tensor_src_grpc (flatbuf) drops a message without the tensor vector.
 */
TEST (nnstreamerGrpc, recvFlatbufNoTensorVector_n)
{
  std::vector<gsize> sizes;
  guint received = _fb_recv (TRUE, 2, NULL, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
}

/**
 * @brief tensor_src_grpc (flatbuf) drops a message declaring more tensors than it carries.
 */
TEST (nnstreamerGrpc, recvFlatbufMissingTensor_n)
{
  std::vector<gsize> sizes;
  const std::vector<gint> bad = { 4 };
  guint received = _fb_recv (TRUE, 2, &bad, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
}

/**
 * @brief tensor_src_grpc (flatbuf) drops a message declaring a negative tensor count.
 */
TEST (nnstreamerGrpc, recvFlatbufNegativeCount_n)
{
  std::vector<gsize> sizes;
  const std::vector<gint> bad = { 4, 2 };
  guint received = _fb_recv (TRUE, -1, &bad, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
}

/**
 * @brief tensor_src_grpc (flatbuf) drops a message whose tensor has no data field.
 */
TEST (nnstreamerGrpc, recvFlatbufNoData_n)
{
  std::vector<gsize> sizes;
  const std::vector<gint> bad = { 4, -1 };
  guint received = _fb_recv (TRUE, 2, &bad, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
}

/**
 * @brief tensor_src_grpc (flatbuf) drops a message whose data size differs from the caps.
 */
TEST (nnstreamerGrpc, recvFlatbufSizeMismatch_n)
{
  std::vector<gsize> sizes;
  const std::vector<gint> bad = { 4, 3 };
  guint received = _fb_recv (TRUE, 2, &bad, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
  EXPECT_EQ (sizes[1], 2U);
}

/**
 * @brief A non-blocking tensor_src_grpc (flatbuf) client receives tensors and ends its call.
 */
TEST (nnstreamerGrpc, nonBlockingClientSrcFlatbuf)
{
  EXPECT_GE (_run_nonblocking_test ("flatbuf", TRUE), 2U);
}

/**
 * @brief A non-blocking tensor_sink_grpc (flatbuf) client sends tensors and ends its call.
 */
TEST (nnstreamerGrpc, nonBlockingClientSinkFlatbuf)
{
  EXPECT_GE (_run_nonblocking_test ("flatbuf", FALSE), 2U);
}
#endif /* ENABLE_FLATBUF */

/**
 * @brief gtest main
 */
int
main (int argc, char **argv)
{
  int result = -1;

  try {
    testing::InitGoogleTest (&argc, argv);
  } catch (...) {
    g_warning ("catch 'testing::internal::<unnamed>::ClassUniqueToAlwaysTrue'");
  }

  gst_init (&argc, &argv);

  try {
    result = RUN_ALL_TESTS ();
  } catch (...) {
    g_warning ("catch `testing::internal::GoogleTestFailureException`");
  }

  return result;
}
