/**
 * @file    unittest_grpc.cc
 * @date    28 Oct 2020
 * @brief   Unit test for gRPC tensor source/sink plugin
 * @see     https://github.com/nnstreamer/nnstreamer
 * @author  Dongju Chae <dongju.chae@samsung.com>
 * @bug     No known bugs
 */

#include <gtest/gtest.h>
#include <glib.h>
#include <gmodule.h>

#include <nnstreamer_conf.h>
#include <nnstreamer_plugin_api.h>
#include <nnstreamer_plugin_api_filter.h>

#include <chrono>
#include <functional>
#include <string>
#include <thread>
#include <vector>

#if defined(ENABLE_PROTOBUF) || defined(ENABLE_FLATBUF)
#include <grpcpp/grpcpp.h>

#include "nnstreamer_grpc.h"
#include "tensor_sink_grpc.h"
#include "tensor_src_grpc.h"
#endif
#ifdef ENABLE_PROTOBUF
#include "nnstreamer.grpc.pb.h" /* Generated by `protoc` */
#endif
#ifdef ENABLE_FLATBUF
#include "nnstreamer.grpc.fb.h" /* Generated by `flatc` */
#endif

#define NNS_GRPC_PLUGIN_NAME "nnstreamer_grpc"
#define NNS_GRPC_TENSOR_SRC_NAME "tensor_src_grpc"
#define NNS_GRPC_TENSOR_SINK_NAME "tensor_sink_grpc"

/**
 * @brief Test gRPC tensor_src/sink existence.
 */
TEST (nnstreamerGrpc, checkExistence)
{
  GstPlugin *plugin;
  GstElementFactory *factory;

  plugin = gst_registry_find_plugin (gst_registry_get (), NNS_GRPC_PLUGIN_NAME);
  EXPECT_TRUE (plugin != NULL);
  gst_object_unref (plugin);

  factory = gst_element_factory_find (NNS_GRPC_TENSOR_SRC_NAME);
  EXPECT_TRUE (factory != NULL);
  gst_object_unref (factory);

  factory = gst_element_factory_find (NNS_GRPC_TENSOR_SINK_NAME);
  EXPECT_TRUE (factory != NULL);
  gst_object_unref (factory);
}

/**
 * @brief Test gRPC tensor_src/sink existence (negative).
 */
TEST (nnstreamerGrpc, checkExistence_n)
{
  GstPlugin *plugin;
  GstElementFactory *factory;
  gchar *name;

  name = g_strconcat (NNS_GRPC_PLUGIN_NAME, "_dummy", NULL);
  plugin = gst_registry_find_plugin (gst_registry_get (), name);
  EXPECT_TRUE (plugin == NULL);
  g_free (name);

  name = g_strconcat (NNS_GRPC_TENSOR_SRC_NAME, "_dummy", NULL);
  factory = gst_element_factory_find (name);
  EXPECT_TRUE (factory == NULL);
  g_free (name);

  name = g_strconcat (NNS_GRPC_TENSOR_SINK_NAME, "_dummy", NULL);
  factory = gst_element_factory_find (name);
  EXPECT_TRUE (factory == NULL);
  g_free (name);
}

/**
 * @brief Test modes.
 */
typedef enum { GRPC_MODE_BOTH = 0, GRPC_MODE_SRC, GRPC_MODE_SINK } TestMode;

/**
 * @brief Test options.
 */
typedef struct {
  gboolean server;
  gchar *host;
  guint port;
  guint fps;
  tensor_type type;
  TestMode mode;
} TestOption;

/**
 * @brief Data structure for test.
 */
typedef struct {
  GMainLoop *loop; /**< main event loop */
  GstElement *pipeline; /**< gst pipeline for test */
} TestData;

/**
 * @brief Data for pipeline and test result.
 */
static TestData test_data;

static gboolean DEFAULT_SERVER = TRUE;
static char DEFAULT_HOST[] = "localhost";
static guint DEFAULT_PORT = 55115;
static guint DEFAULT_FPS = 10;
static guint DEFAULT_OUT = 0;
static tensor_type DEFAULT_TYPE = _NNS_UINT8;

/**
 * @brief Prepare test pipeline
 */
static gboolean
_setup_pipeline (TestOption &option)
{
  gchar *str_pipeline;

  switch (option.mode) {
    case GRPC_MODE_SRC:
      str_pipeline = g_strdup_printf ("tensor_src_grpc name=src server=%s host=%s port=%u ! "
                                      "other/tensor,dimension=(string)1:1:1:1,type=(string)%s,framerate=(fraction)%u/1 ! "
                                      "fakesink",
          option.server ? "TRUE" : "FALSE", option.host, option.port,
          gst_tensor_get_type_string (option.type), option.fps);
      break;
    case GRPC_MODE_SINK:
      str_pipeline = g_strdup_printf (
          "videotestsrc ! video/x-raw,format=RGB,width=640,height=480,framerate=%u/1 !"
          "tensor_converter ! tensor_sink_grpc name=sink server=%s host=%s port=%u",
          option.fps, option.server ? "TRUE" : "FALSE", option.host, option.port);
      break;
    default:
      return FALSE;
  }

  test_data.pipeline = gst_parse_launch (str_pipeline, NULL);
  g_free (str_pipeline);

  return test_data.pipeline != NULL ? TRUE : FALSE;
}

/**
 * @brief set default option
 */
static void
_set_default_option (TestOption &option)
{
  option.server = DEFAULT_SERVER;
  option.host = DEFAULT_HOST;
  option.port = DEFAULT_PORT;
  option.fps = DEFAULT_FPS;
  option.type = DEFAULT_TYPE;
  option.mode = GRPC_MODE_BOTH;
}

/**
 * @brief Test gRPC tensor_src get default property
 */
TEST (nnstreamerGrpc, srcGetPropertyDefault)
{
  TestOption option;
  GstElement *src;
  gboolean silent, server;
  guint port, out;
  gchar *host;

  _set_default_option (option);
  option.mode = GRPC_MODE_SRC;

  ASSERT_TRUE (_setup_pipeline (option));

  src = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "src");
  ASSERT_TRUE (src != NULL);

  g_object_get (src, "silent", &silent, NULL);
  EXPECT_TRUE (silent);

  g_object_get (src, "server", &server, NULL);
  EXPECT_EQ (server, DEFAULT_SERVER);

  g_object_get (src, "host", &host, NULL);
  EXPECT_STREQ (host, DEFAULT_HOST);
  g_free (host);

  g_object_get (src, "port", &port, NULL);
  EXPECT_EQ (port, DEFAULT_PORT);

  g_object_get (src, "out", &out, NULL);
  EXPECT_EQ (out, DEFAULT_OUT);

  gst_object_unref (src);
  gst_object_unref (test_data.pipeline);
}

/**
 * @brief Test gRPC tensor_sink get default property
 */
TEST (nnstreamerGrpc, sinkGetPropertyDefault)
{
  TestOption option;
  GstElement *sink;
  gboolean silent, server;
  guint port, out, stop_timeout;
  gchar *host;

  _set_default_option (option);
  option.mode = GRPC_MODE_SINK;

  ASSERT_TRUE (_setup_pipeline (option));

  sink = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "sink");
  ASSERT_TRUE (sink != NULL);

  g_object_get (sink, "silent", &silent, NULL);
  EXPECT_TRUE (silent);

  g_object_get (sink, "server", &server, NULL);
  EXPECT_EQ (server, DEFAULT_SERVER);

  g_object_get (sink, "host", &host, NULL);
  EXPECT_STREQ (host, DEFAULT_HOST);
  g_free (host);

  g_object_get (sink, "port", &port, NULL);
  EXPECT_EQ (port, DEFAULT_PORT);

  g_object_get (sink, "out", &out, NULL);
  EXPECT_EQ (out, DEFAULT_OUT);

  g_object_get (sink, "stop-timeout", &stop_timeout, NULL);
  EXPECT_EQ (stop_timeout, 5000U);

  gst_object_unref (sink);
  gst_object_unref (test_data.pipeline);
}

/**
 * @brief Test gRPC tensor_src set property
 */
TEST (nnstreamerGrpc, srcSetProperty)
{
  TestOption option;
  GstElement *src;
  gboolean silent, server;
  guint port;
  gchar *host;

  _set_default_option (option);
  option.mode = GRPC_MODE_SRC;

  ASSERT_TRUE (_setup_pipeline (option));

  src = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "src");
  ASSERT_TRUE (src != NULL);

  g_object_set (src, "silent", (gboolean) FALSE, NULL);
  g_object_get (src, "silent", &silent, NULL);
  EXPECT_TRUE (!silent);

  g_object_set (src, "server", (gboolean) FALSE, NULL);
  g_object_get (src, "server", &server, NULL);
  EXPECT_TRUE (!server);

  g_object_set (src, "host", "1.1.1.1", NULL);
  g_object_get (src, "host", &host, NULL);
  EXPECT_STREQ (host, "1.1.1.1");
  g_free (host);

  g_object_set (src, "port", 1000, NULL);
  g_object_get (src, "port", &port, NULL);
  EXPECT_EQ (port, 1000U);

  gst_object_unref (src);
  gst_object_unref (test_data.pipeline);
}

/**
 * @brief Test gRPC tensor_sink set property
 */
TEST (nnstreamerGrpc, sinkSetProperty)
{
  TestOption option;
  GstElement *sink;
  gboolean silent, server;
  guint port, stop_timeout;
  gchar *host;

  _set_default_option (option);
  option.mode = GRPC_MODE_SINK;

  ASSERT_TRUE (_setup_pipeline (option));

  sink = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "sink");
  ASSERT_TRUE (sink != NULL);

  g_object_set (sink, "silent", (gboolean) FALSE, NULL);
  g_object_get (sink, "silent", &silent, NULL);
  EXPECT_TRUE (!silent);

  g_object_set (sink, "server", (gboolean) FALSE, NULL);
  g_object_get (sink, "server", &server, NULL);
  EXPECT_TRUE (!server);

  g_object_set (sink, "host", "1.1.1.1", NULL);
  g_object_get (sink, "host", &host, NULL);
  EXPECT_STREQ (host, "1.1.1.1");
  g_free (host);

  g_object_set (sink, "port", 1000, NULL);
  g_object_get (sink, "port", &port, NULL);
  EXPECT_EQ (port, 1000U);

  g_object_set (sink, "stop-timeout", 1234U, NULL);
  g_object_get (sink, "stop-timeout", &stop_timeout, NULL);
  EXPECT_EQ (stop_timeout, 1234U);

  gst_object_unref (sink);
  gst_object_unref (test_data.pipeline);
}

/**
 * @brief Test gRPC tensor_src invalid host
 */
TEST (nnstreamerGrpc, srcInvalidHost_n)
{
  TestOption option;
  GstElement *src;
  gchar *host;

  _set_default_option (option);
  option.mode = GRPC_MODE_SRC;

  ASSERT_TRUE (_setup_pipeline (option));

  src = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "src");
  ASSERT_TRUE (src != NULL);

  g_object_set (src, "host", "invalid host", NULL);
  g_object_get (src, "host", &host, NULL);
  EXPECT_STREQ (host, DEFAULT_HOST);
  g_free (host);

  gst_object_unref (src);
  gst_object_unref (test_data.pipeline);
}

/**
 * @brief Test gRPC tensor_sink invalid host
 */
TEST (nnstreamerGrpc, sinkInvalidHost_n)
{
  TestOption option;
  GstElement *sink;
  gchar *host;

  _set_default_option (option);
  option.mode = GRPC_MODE_SINK;

  ASSERT_TRUE (_setup_pipeline (option));

  sink = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "sink");
  ASSERT_TRUE (sink != NULL);

  g_object_set (sink, "host", "invalid host", NULL);
  g_object_get (sink, "host", &host, NULL);
  EXPECT_STREQ (host, DEFAULT_HOST);
  g_free (host);

  gst_object_unref (sink);
  gst_object_unref (test_data.pipeline);
}

/**
 * @brief Test gRPC tensor_src invalid port
 */
TEST (nnstreamerGrpc, srcInvalidPort_n)
{
  TestOption option;
  GstElement *src;
  guint port;

  _set_default_option (option);
  option.mode = GRPC_MODE_SRC;

  ASSERT_TRUE (_setup_pipeline (option));

  src = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "src");
  ASSERT_TRUE (src != NULL);

  g_object_set (src, "port", G_MAXUSHORT + 1, NULL);
  g_object_get (src, "port", &port, NULL);
  EXPECT_EQ (port, DEFAULT_PORT);

  g_object_set (src, "port", "5555", NULL);
  g_object_get (src, "port", &port, NULL);
  EXPECT_EQ (port, DEFAULT_PORT);

  gst_object_unref (src);
  gst_object_unref (test_data.pipeline);
}

/**
 * @brief Test gRPC tensor_sink invalid port
 */
TEST (nnstreamerGrpc, sinkInvalidPort_n)
{
  TestOption option;
  GstElement *sink;
  guint port;

  _set_default_option (option);
  option.mode = GRPC_MODE_SINK;

  ASSERT_TRUE (_setup_pipeline (option));

  sink = gst_bin_get_by_name (GST_BIN (test_data.pipeline), "sink");
  ASSERT_TRUE (sink != NULL);

  g_object_set (sink, "port", G_MAXUSHORT + 1, NULL);
  g_object_get (sink, "port", &port, NULL);
  EXPECT_EQ (port, DEFAULT_PORT);

  g_object_set (sink, "port", "5555", NULL);
  g_object_get (sink, "port", &port, NULL);
  EXPECT_EQ (port, DEFAULT_PORT);

  gst_object_unref (sink);
  gst_object_unref (test_data.pipeline);
}

#if defined(ENABLE_PROTOBUF) || defined(ENABLE_FLATBUF)
/**
 * @brief Address of the TEST-NET-1 block; no local interface can bind to it.
 */
#define UNBINDABLE_HOST "192.0.2.1"

/**
 * @brief Caps of the pipelines that stream one uint8 tensor of a 16x16 RGB frame.
 */
#define STREAM_VIDEO_CAPS \
  "video/x-raw,format=RGB,width=16,height=16,framerate=30/1"
#define STREAM_TENSOR_CAPS \
  "other/tensor,dimension=3:16:16,type=uint8,framerate=30/1"

/**
 * @brief Get the gRPC instance tensor_src_grpc holds, NULL if it holds none.
 */
static void *
_src_grpc_instance (GstElement *element)
{
  return ((grpc_private *) ((GstTensorSrcGRPC *) element)->priv)->instance;
}

/**
 * @brief Get the gRPC instance tensor_sink_grpc holds, NULL if it holds none.
 */
static void *
_sink_grpc_instance (GstElement *element)
{
  return ((grpc_private *) ((GstTensorSinkGRPC *) element)->priv)->instance;
}

/**
 * @brief Build a gRPC element and bring it to PAUSED, where start () has run.
 * @return the state change result; the element is returned in @a element
 */
static GstStateChangeReturn
_start_grpc_element (const gchar *name, const gchar *host, GstElement **element)
{
  GstElement *e = gst_element_factory_make (name, NULL);

  if (!e)
    return GST_STATE_CHANGE_FAILURE;

  g_object_set (e, "server", (gboolean) TRUE, "host", host, "port", 0, NULL);
  *element = e;

  return gst_element_set_state (e, GST_STATE_PAUSED);
}

/**
 * @brief Wait until the source pad of @a element has negotiated its caps.
 */
static gboolean
_wait_for_caps (GstElement *element)
{
  GstPad *pad = gst_element_get_static_pad (element, "src");
  GstCaps *caps = NULL;
  guint i;

  for (i = 0; i < 1000 && !caps; i++) {
    caps = gst_pad_get_current_caps (pad);
    if (!caps)
      g_usleep (10000);
  }
  gst_object_unref (pad);

  if (!caps)
    return FALSE;

  gst_caps_unref (caps);
  return TRUE;
}

/**
 * @brief The element flags must not alias any flag of their base class.
 *
 * Every bit a base class may take is below the FLAG_LAST it declares; GstBaseSink
 * declares none of its own, so GstElement's is the bound of the sink.
 */
TEST (nnstreamerGrpc, elementFlags)
{
  guint src_base = (guint) GST_BASE_SRC_FLAG_LAST - 1;
  guint sink_base = (guint) GST_ELEMENT_FLAG_LAST - 1;

  EXPECT_EQ ((guint) GST_TENSOR_SRC_GRPC_CONFIGURED & src_base, 0U);
  EXPECT_EQ ((guint) GST_TENSOR_SRC_GRPC_STARTED & src_base, 0U);
  EXPECT_EQ ((guint) GST_TENSOR_SINK_GRPC_CONFIGURED & sink_base, 0U);
  EXPECT_EQ ((guint) GST_TENSOR_SINK_GRPC_STARTED & sink_base, 0U);
}

/**
 * @brief tensor_src_grpc releases its gRPC instance when the element stops.
 */
TEST (nnstreamerGrpc, srcReleasesInstance)
{
  GstElement *src = NULL;

  ASSERT_NE (_start_grpc_element ("tensor_src_grpc", "localhost", &src), GST_STATE_CHANGE_FAILURE);
  EXPECT_TRUE (_src_grpc_instance (src) != NULL);

  gst_element_set_state (src, GST_STATE_NULL);
  EXPECT_TRUE (_src_grpc_instance (src) == NULL);

  gst_object_unref (src);
}

/**
 * @brief tensor_sink_grpc releases its gRPC instance when the element stops.
 */
TEST (nnstreamerGrpc, sinkReleasesInstance)
{
  GstElement *sink = NULL;

  ASSERT_NE (_start_grpc_element ("tensor_sink_grpc", "localhost", &sink),
      GST_STATE_CHANGE_FAILURE);
  EXPECT_TRUE (_sink_grpc_instance (sink) != NULL);

  gst_element_set_state (sink, GST_STATE_NULL);
  EXPECT_TRUE (_sink_grpc_instance (sink) == NULL);

  gst_object_unref (sink);
}

/**
 * @brief tensor_src_grpc fails to start and holds no instance when its server cannot listen.
 */
TEST (nnstreamerGrpc, srcStartFailure_n)
{
  GstElement *src = NULL;

  EXPECT_EQ (_start_grpc_element ("tensor_src_grpc", UNBINDABLE_HOST, &src),
      GST_STATE_CHANGE_FAILURE);
  ASSERT_TRUE (src != NULL);
  EXPECT_TRUE (_src_grpc_instance (src) == NULL);

  gst_element_set_state (src, GST_STATE_NULL);
  gst_object_unref (src);
}

/**
 * @brief tensor_sink_grpc fails to start and holds no instance when its server cannot listen.
 */
TEST (nnstreamerGrpc, sinkStartFailure_n)
{
  GstElement *sink = NULL;

  EXPECT_EQ (_start_grpc_element ("tensor_sink_grpc", UNBINDABLE_HOST, &sink),
      GST_STATE_CHANGE_FAILURE);
  ASSERT_TRUE (sink != NULL);
  EXPECT_TRUE (_sink_grpc_instance (sink) == NULL);

  gst_element_set_state (sink, GST_STATE_NULL);
  gst_object_unref (sink);
}

/**
 * @brief Static caps of the received-message tests: two uint8 tensors of 4 and 2 bytes.
 */
#define RECV_STATIC_CAPS \
  "other/tensors,num_tensors=2,dimensions=4:1:1:1.2:1:1:1,types=uint8.uint8,framerate=30/1"

/**
 * @brief Buffers tensor_sink got from tensor_src_grpc.
 */
typedef struct {
  GMutex lock; /**< protects the fields below */
  guint received; /**< number of buffers */
  std::vector<gsize> sizes; /**< memory sizes of the last buffer */
} RecvData;

/**
 * @brief tensor_sink new-data callback, records the memory sizes of the buffer.
 */
static void
_recv_new_data_cb (GstElement *element, GstBuffer *buffer, gpointer user_data)
{
  RecvData *data = (RecvData *) user_data;
  guint i, num;

  g_mutex_lock (&data->lock);
  data->received++;
  data->sizes.clear ();
  num = gst_tensor_buffer_get_count (buffer);
  for (i = 0; i < num; i++) {
    GstMemory *mem = gst_tensor_buffer_get_nth_memory (buffer, i);
    data->sizes.push_back (gst_memory_get_sizes (mem, NULL, NULL));
    gst_memory_unref (mem);
  }
  g_mutex_unlock (&data->lock);
}

/**
 * @brief Sends messages to the given address; calls the given function to wait for the buffers before closing the call.
 */
typedef std::function<void (const std::string &, const std::function<void ()> &)> RecvSendFunc;

/**
 * @brief Run tensor_src_grpc as a server, let @a send stream messages to it, and wait for @a expected buffers.
 * @return the number of buffers tensor_sink received (G_MAXUINT if the server did not start), the memory sizes of the last one in @a sizes.
 */
static guint
_run_recv_test (const gchar *idl, const std::string &caps,
    const RecvSendFunc &send, guint expected, std::vector<gsize> &sizes)
{
  GstElement *pipeline, *src, *sink;
  GstPad *pad;
  GstCaps *current = NULL;
  RecvData data;
  gchar *str;
  gint port = 0;
  guint i, received;

  str = g_strdup_printf ("tensor_src_grpc name=src server=TRUE blocking=TRUE idl=%s host=localhost port=0 ! %s ! "
                         "tensor_sink name=sink emit-signal=TRUE sync=FALSE async=FALSE",
      idl, caps.c_str ());
  pipeline = gst_parse_launch (str, NULL);
  g_free (str);
  if (!pipeline)
    return G_MAXUINT;

  g_mutex_init (&data.lock);
  data.received = 0;

  src = gst_bin_get_by_name (GST_BIN (pipeline), "src");
  sink = gst_bin_get_by_name (GST_BIN (pipeline), "sink");
  g_signal_connect (sink, "new-data", G_CALLBACK (_recv_new_data_cb), &data);

  gst_element_set_state (pipeline, GST_STATE_PLAYING);

  /* the server has started and the caps are set once the pad has them */
  pad = gst_element_get_static_pad (src, "src");
  for (i = 0; i < 1000 && !current; i++) {
    current = gst_pad_get_current_caps (pad);
    if (!current)
      g_usleep (10000);
  }
  gst_object_unref (pad);

  if (current) {
    gst_caps_unref (current);
    g_object_get (src, "port", &port, NULL);
    send ("localhost:" + std::to_string (port), [&] () {
      for (i = 0; i < 1000; i++) {
        g_mutex_lock (&data.lock);
        received = data.received;
        g_mutex_unlock (&data.lock);
        if (received >= expected)
          break;
        g_usleep (10000);
      }
    });
  }

  gst_element_set_state (pipeline, GST_STATE_NULL);

  received = data.received;
  sizes = data.sizes;

  gst_object_unref (src);
  gst_object_unref (sink);
  gst_object_unref (pipeline);
  g_mutex_clear (&data.lock);

  return current ? received : G_MAXUINT;
}

/**
 * @brief Wait until @a data has @a expected buffers, at most 10 seconds.
 */
static guint
_wait_for_buffers (RecvData &data, guint expected)
{
  guint i, received = 0;

  for (i = 0; i < 1000; i++) {
    g_mutex_lock (&data.lock);
    received = data.received;
    g_mutex_unlock (&data.lock);
    if (received >= expected)
      break;
    g_usleep (10000);
  }

  return received;
}

/**
 * @brief Reader of the client-call counters a gRPC sub-plugin exports.
 */
typedef void (*grpc_call_stats_fn) (gint *live, gint *unfinished);

/**
 * @brief Open the sub-plugin of @a idl and keep it loaded while a test runs.
 * @param[out] stats its counter reader, NULL if the sub-plugin exports none
 * @return the module, NULL if it cannot be opened
 *
 * The element closes its own handle when it releases the instance, which
 * unloads the sub-plugin and resets the counters; the caller has to hold a
 * handle of its own across the run to read them afterwards.
 */
static GModule *
_open_grpc_idl_module (const gchar *idl, grpc_call_stats_fn *stats)
{
  gchar *name = g_strdup_printf ("libnnstreamer_grpc_%s%s", idl, NNSTREAMER_SO_FILE_EXTENSION);
  GModule *module = g_module_open (name, G_MODULE_BIND_LAZY);

  *stats = NULL;
  if (module && !g_module_symbol (module, "nnstreamer_grpc_get_client_call_stats", (gpointer *) stats))
    *stats = NULL;

  g_free (name);

  return module;
}

/**
 * @brief Wait until no buffer has arrived for 200 ms, at most 2 seconds.
 */
static void
_wait_for_stream_end (RecvData &data)
{
  guint i, now, last = 0, stable = 0;

  for (i = 0; i < 100 && stable < 10; i++) {
    g_usleep (20000);
    g_mutex_lock (&data.lock);
    now = data.received;
    g_mutex_unlock (&data.lock);
    stable = (now == last) ? stable + 1 : 0;
    last = now;
  }
}

/**
 * @brief Stream tensors between a blocking server and a non-blocking (async) client.
 * @param idl the IDL both ends use
 * @param client_src TRUE to let tensor_src_grpc be the client, FALSE to let tensor_sink_grpc be it
 * @return the number of buffers tensor_sink got, 0 if a pipeline did not build or start
 *
 * The peer of the client is torn down first, so that the client handles the
 * end of the stream while its completion queue still has a batch outstanding.
 * Every client call of the run has to be gone by the end of it, and none of
 * them may have been freed while its completion queue still held a batch.
 */
static guint
_run_nonblocking_test (const gchar *idl, gboolean client_src)
{
  GstElement *server, *client, *grpc, *sink = NULL;
  grpc_call_stats_fn stats;
  GModule *module;
  RecvData data;
  gchar *str;
  gint port = 0;
  gint live_before = 0, unfinished_before = 0, live = 0, unfinished = 0;
  guint received;

  if (client_src)
    str = g_strdup_printf ("videotestsrc num-buffers=10 ! " STREAM_VIDEO_CAPS " ! tensor_converter ! "
                           "tensor_sink_grpc name=grpc server=TRUE blocking=TRUE idl=%s "
                           "host=localhost port=0 async=FALSE",
        idl);
  else
    str = g_strdup_printf ("tensor_src_grpc name=grpc server=TRUE blocking=TRUE idl=%s "
                           "host=localhost port=0 ! " STREAM_TENSOR_CAPS
                           " ! tensor_sink name=sink emit-signal=TRUE sync=FALSE async=FALSE",
        idl);
  server = gst_parse_launch (str, NULL);
  g_free (str);
  if (!server) {
    ADD_FAILURE () << "the server pipeline of the " << idl << " test did not build";
    return 0;
  }

  module = _open_grpc_idl_module (idl, &stats);
  EXPECT_TRUE (module != NULL);
  EXPECT_TRUE (stats != NULL);
  if (stats)
    stats (&live_before, &unfinished_before);

  g_mutex_init (&data.lock);
  data.received = 0;

  grpc = gst_bin_get_by_name (GST_BIN (server), "grpc");
  gst_element_set_state (server, GST_STATE_PLAYING);

  if (client_src)
    gst_element_get_state (server, NULL, NULL, 10 * GST_SECOND);
  else if (_wait_for_caps (grpc)) {
    sink = gst_bin_get_by_name (GST_BIN (server), "sink");
    g_signal_connect (sink, "new-data", G_CALLBACK (_recv_new_data_cb), &data);
    gst_object_unref (sink);
  }

  g_object_get (grpc, "port", &port, NULL);
  gst_object_unref (grpc);

  /* the server did not start; nothing has been queued for it either */
  if (port <= 0) {
    ADD_FAILURE () << "the " << idl << " server did not get a port to listen on";
    gst_element_set_state (server, GST_STATE_NULL);
    gst_object_unref (server);
    g_mutex_clear (&data.lock);
    if (module)
      g_module_close (module);
    return 0;
  }

  if (client_src)
    str = g_strdup_printf (
        "tensor_src_grpc server=FALSE blocking=FALSE idl=%s host=localhost port=%d ! " STREAM_TENSOR_CAPS
        " ! tensor_sink name=sink emit-signal=TRUE sync=FALSE async=FALSE",
        idl, port);
  else
    str = g_strdup_printf (
        "videotestsrc num-buffers=10 ! " STREAM_VIDEO_CAPS " ! tensor_converter ! "
        "tensor_sink_grpc server=FALSE blocking=FALSE idl=%s host=localhost port=%d",
        idl, port);
  client = gst_parse_launch (str, NULL);
  g_free (str);
  if (!client)
    ADD_FAILURE () << "the client pipeline of the " << idl << " test did not build";

  if (client) {
    if (client_src) {
      sink = gst_bin_get_by_name (GST_BIN (client), "sink");
      g_signal_connect (sink, "new-data", G_CALLBACK (_recv_new_data_cb), &data);
      gst_object_unref (sink);
    }
    gst_element_set_state (client, GST_STATE_PLAYING);
  }

  received = _wait_for_buffers (data, 2);

  /* the peer leaves first; the client has to finish its call on its own */
  if (client_src) {
    gst_element_set_state (server, GST_STATE_NULL);
    _wait_for_stream_end (data);
    if (client)
      gst_element_set_state (client, GST_STATE_NULL);
  } else {
    if (client)
      gst_element_set_state (client, GST_STATE_NULL);
    gst_element_set_state (server, GST_STATE_NULL);
  }

  /* the elements have joined their worker threads by now */
  if (stats) {
    stats (&live, &unfinished);
    EXPECT_EQ (live, live_before);
    EXPECT_EQ (unfinished, unfinished_before);
  }

  if (client)
    gst_object_unref (client);
  gst_object_unref (server);
  g_mutex_clear (&data.lock);
  if (module)
    g_module_close (module);

  return client ? received : 0;
}

/**
 * @brief A state change to NULL, run in a thread of its own so that a hang can be detected.
 */
typedef struct {
  GstElement *element; /**< the element to bring to NULL */
  gint done; /**< set once the state change has returned */
} StopData;

/**
 * @brief Thread body: bring the element to NULL and tell when it returns.
 */
static gpointer
_set_null_thread (gpointer user_data)
{
  StopData *stop = (StopData *) user_data;

  gst_element_set_state (stop->element, GST_STATE_NULL);
  g_atomic_int_set (&stop->done, 1);

  return NULL;
}

/**
 * @brief Bring @a pipeline to NULL and release it, if the state change returns within 10 seconds.
 * @return TRUE if it returned in time
 *
 * On a hang the pipeline and the thread stuck in its state change are left
 * behind, so that the test fails instead of blocking the whole binary.
 */
static gboolean
_set_null_in_time (GstElement *pipeline)
{
  StopData *stop = g_new0 (StopData, 1);
  GThread *thread;
  guint i;

  stop->element = pipeline;
  thread = g_thread_new ("grpc-stop", _set_null_thread, stop);

  for (i = 0; i < 1000 && !g_atomic_int_get (&stop->done); i++)
    g_usleep (10000);

  if (!g_atomic_int_get (&stop->done)) {
    g_thread_unref (thread);
    return FALSE;
  }

  g_thread_join (thread);
  g_free (stop);
  gst_object_unref (pipeline);

  return TRUE;
}

/**
 * @brief Run tensor_sink_grpc until every buffer of a finite stream has been queued in it.
 * @param video_caps the caps of the raw frames
 * @param num the number of frames
 * @param options the properties of tensor_sink_grpc
 * @return the pipeline at EOS, NULL if it did not build
 */
static GstElement *
_queue_in_sink (const gchar *video_caps, guint num, const gchar *options)
{
  GstElement *pipeline;
  GstMessage *msg;
  GstBus *bus;
  gchar *str;

  str = g_strdup_printf ("videotestsrc num-buffers=%u ! %s ! tensor_converter ! "
                         "tensor_sink_grpc name=grpc host=localhost async=FALSE %s",
      num, video_caps, options);
  pipeline = gst_parse_launch (str, NULL);
  g_free (str);
  if (!pipeline)
    return NULL;

  /* the sink renders a buffer by queueing it, so all are queued once it has the EOS */
  EXPECT_NE (gst_element_set_state (pipeline, GST_STATE_PLAYING), GST_STATE_CHANGE_FAILURE);
  bus = gst_element_get_bus (pipeline);
  msg = gst_bus_timed_pop_filtered (bus, 10 * GST_SECOND,
      (GstMessageType) (GST_MESSAGE_EOS | GST_MESSAGE_ERROR));
  EXPECT_TRUE (msg != NULL && GST_MESSAGE_TYPE (msg) == GST_MESSAGE_EOS);
  if (msg)
    gst_message_unref (msg);
  gst_object_unref (bus);

  return pipeline;
}

/**
 * @brief Get a local port nobody listens on: a server takes a free one and shuts down.
 * @return the port, 0 if no server could start
 */
static int
_unused_port (void)
{
  grpc::ServerBuilder builder;
  void *tag;
  bool ok;
  int port = 0;

  /* a server with no service needs a completion queue to start */
  builder.AddListeningPort ("localhost:0", grpc::InsecureServerCredentials (), &port);
  auto cq = builder.AddCompletionQueue ();
  auto server = builder.BuildAndStart ();
  if (server)
    server->Shutdown ();

  cq->Shutdown ();
  while (cq->Next (&tag, &ok))
    ;

  return server ? port : 0;
}

/**
 * @brief Queue buffers in tensor_sink_grpc that no peer takes, then bring it to NULL.
 * @param idl the IDL of the sink
 * @param server TRUE to run the sink as a server nobody connects to, FALSE as a client of a port nobody listens on
 * @param blocking the blocking property of the sink
 * @return TRUE if the change to NULL returned within 10 seconds
 */
static gboolean
_stop_undrained_sink (const gchar *idl, gboolean server, gboolean blocking)
{
  GstElement *pipeline;
  gchar *options;
  int port = 0;

  if (!server) {
    port = _unused_port ();
    if (port <= 0) {
      ADD_FAILURE () << "no free local port for the " << idl << " client";
      return FALSE;
    }
  }

  options = g_strdup_printf ("server=%s blocking=%s idl=%s port=%d",
      server ? "TRUE" : "FALSE", blocking ? "TRUE" : "FALSE", idl, port);
  pipeline = _queue_in_sink (STREAM_VIDEO_CAPS, 5, options);
  g_free (options);
  if (!pipeline) {
    ADD_FAILURE () << "the " << idl << " sink pipeline did not build";
    return FALSE;
  }

  return _set_null_in_time (pipeline);
}

/**
 * @brief Bring a tensor_src_grpc client to NULL while its server sends nothing.
 * @param idl the IDL of both ends
 * @param blocking the blocking property of the client
 * @return TRUE if the change to NULL returned within 10 seconds
 */
static gboolean
_stop_client_src_of_idle_server (const gchar *idl, gboolean blocking)
{
  GstElement *server, *client;
  gchar *str;
  gint port = 0;
  gboolean stopped = FALSE;

  server = gst_element_factory_make ("tensor_sink_grpc", NULL);
  if (!server) {
    ADD_FAILURE () << "tensor_sink_grpc is not available";
    return FALSE;
  }
  g_object_set (server, "server", (gboolean) TRUE, "idl", idl, "host",
      "localhost", "port", 0, NULL);
  EXPECT_NE (gst_element_set_state (server, GST_STATE_PAUSED), GST_STATE_CHANGE_FAILURE);
  g_object_get (server, "port", &port, NULL);
  EXPECT_GT (port, 0);

  str = g_strdup_printf ("tensor_src_grpc server=FALSE blocking=%s idl=%s host=localhost port=%d ! " STREAM_TENSOR_CAPS
                         " ! fakesink async=FALSE",
      blocking ? "TRUE" : "FALSE", idl, port);
  client = gst_parse_launch (str, NULL);
  g_free (str);

  if (client) {
    EXPECT_NE (gst_element_set_state (client, GST_STATE_PLAYING), GST_STATE_CHANGE_FAILURE);
    /* let the client call reach the server */
    g_usleep (G_USEC_PER_SEC / 2);
    stopped = _set_null_in_time (client);
  } else {
    ADD_FAILURE () << "the " << idl << " client pipeline did not build";
  }

  gst_element_set_state (server, GST_STATE_NULL);
  gst_object_unref (server);

  return stopped;
}

/**
 * @brief State shared by a test and a raw gRPC peer it runs in a thread.
 */
typedef struct {
  gint count; /**< the messages the peer has read, or 1 once it holds an idle call */
  gint release; /**< set by the test to let an idle peer close its call */
} PeerState;

/**
 * @brief A raw gRPC peer: runs one call against the address, reporting in the state.
 */
typedef std::function<void (const std::string &, PeerState *)> PeerFunc;

/**
 * @brief Frames large enough that the transport cannot buffer all of them at once.
 */
#define LARGE_VIDEO_CAPS \
  "video/x-raw,format=RGB,width=1280,height=720,framerate=30/1"
#define LARGE_FRAMES 10

/**
 * @brief How long a slow peer pauses before each message it reads.
 */
#define PEER_READ_DELAY_US 50000

/**
 * @brief Hold an idle peer until the test releases it, at most 25 seconds.
 */
static void
_wait_for_release (PeerState *state)
{
  guint i;

  for (i = 0; i < 2500 && !g_atomic_int_get (&state->release); i++)
    g_usleep (10000);
}

/**
 * @brief Wait until the peer has read a message or holds its call, at most 10 seconds.
 */
static gboolean
_wait_for_peer (PeerState *state)
{
  guint i;

  for (i = 0; i < 1000 && g_atomic_int_get (&state->count) == 0; i++)
    g_usleep (10000);

  return g_atomic_int_get (&state->count) > 0;
}

/**
 * @brief Get the port the element named "grpc" in @a pipeline listens on.
 */
static gint
_grpc_port (GstElement *pipeline)
{
  GstElement *grpc = gst_bin_get_by_name (GST_BIN (pipeline), "grpc");
  gint port = 0;

  g_object_get (grpc, "port", &port, NULL);
  gst_object_unref (grpc);

  return port;
}

/**
 * @brief Queue large frames in a tensor_sink_grpc server, run @a peer on its
 * stream, and bring the sink to NULL once the peer has a message.
 * @param idl the IDL of the sink
 * @param blocking the blocking property of the sink
 * @param peer the peer reading the stream
 * @param[out] state the state of the peer after the run
 * @return TRUE if the change to NULL returned within 10 seconds
 */
static gboolean
_stop_server_sink_with_peer (
    const gchar *idl, gboolean blocking, const PeerFunc &peer, PeerState *state)
{
  GstElement *pipeline;
  gchar *options;
  gint port;
  gboolean stopped;

  options = g_strdup_printf (
      "server=TRUE blocking=%s idl=%s port=0", blocking ? "TRUE" : "FALSE", idl);
  pipeline = _queue_in_sink (LARGE_VIDEO_CAPS, LARGE_FRAMES, options);
  g_free (options);
  if (!pipeline) {
    ADD_FAILURE () << "the " << idl << " sink pipeline did not build";
    return FALSE;
  }

  port = _grpc_port (pipeline);
  EXPECT_GT (port, 0);

  std::thread reader (peer, "localhost:" + std::to_string (port), state);

  EXPECT_TRUE (_wait_for_peer (state));
  stopped = _set_null_in_time (pipeline);

  g_atomic_int_set (&state->release, 1);
  reader.join ();

  return stopped;
}

/**
 * @brief Queue frames in a tensor_sink_grpc client of @a service, and
 * bring the sink to NULL once the server has the call.
 * @param idl the IDL of the sink and the service
 * @param blocking the blocking property of the sink
 * @param video_caps the caps of the raw frames
 * @param num the number of frames
 * @param extra more properties of the sink
 * @param service the server side of the call, reporting in @a state
 * @param state the state @a service reports in
 * @return TRUE if the change to NULL returned within 10 seconds
 */
static gboolean
_stop_client_sink_stream (const gchar *idl, gboolean blocking, const gchar *video_caps,
    guint num, const gchar *extra, grpc::Service *service, PeerState *state)
{
  grpc::ServerBuilder builder;
  GstElement *pipeline;
  gchar *options;
  int port = 0;
  gboolean stopped = FALSE;

  builder.AddListeningPort ("localhost:0", grpc::InsecureServerCredentials (), &port);
  builder.RegisterService (service);
  auto server = builder.BuildAndStart ();
  if (!server) {
    ADD_FAILURE () << "the " << idl << " peer server did not start";
    return FALSE;
  }

  options = g_strdup_printf ("server=FALSE blocking=%s idl=%s port=%d %s",
      blocking ? "TRUE" : "FALSE", idl, port, extra);
  pipeline = _queue_in_sink (video_caps, num, options);
  g_free (options);

  if (pipeline) {
    EXPECT_TRUE (_wait_for_peer (state));
    stopped = _set_null_in_time (pipeline);
  } else {
    ADD_FAILURE () << "the " << idl << " sink pipeline did not build";
  }

  g_atomic_int_set (&state->release, 1);
  server->Shutdown (std::chrono::system_clock::now () + std::chrono::seconds (5));

  return stopped;
}

/**
 * @brief Run _stop_client_sink_stream () with large frames, which the transport cannot hold.
 */
static gboolean
_stop_client_sink_with_server (const gchar *idl, gboolean blocking,
    grpc::Service *service, PeerState *state)
{
  return _stop_client_sink_stream (
      idl, blocking, LARGE_VIDEO_CAPS, LARGE_FRAMES, "", service, state);
}

/**
 * @brief The number of small frames a slow server needs about 3 seconds to
 * read, which the transport holds as a whole.
 */
#define SMALL_FRAMES 60

/**
 * @brief Stream small frames at once from a blocking tensor_sink_grpc client to
 * @a service, which reads slowly, and bring the sink to NULL.
 * @param idl the IDL of the sink and the service
 * @param extra more properties of the sink
 * @param service the server side of the call, reporting in @a state
 * @param state the state @a service reports in
 * @return the number of messages the server has read when the sink is at NULL, -1 if it did not get there
 */
static gint
_stop_client_sink_small_frames (const gchar *idl, const gchar *extra,
    grpc::Service *service, PeerState *state)
{
  gchar *options = g_strdup_printf ("sync=FALSE %s", extra);
  gboolean stopped = _stop_client_sink_stream (
      idl, TRUE, STREAM_VIDEO_CAPS, SMALL_FRAMES, options, service, state);

  g_free (options);

  return stopped ? g_atomic_int_get (&state->count) : -1;
}

/**
 * @brief Run tensor_src_grpc as a server, let @a peer open a call that sends nothing, and bring the source to NULL.
 * @param idl the IDL of the source
 * @param blocking the blocking property of the source
 * @param peer the client holding an idle call
 * @return TRUE if the change to NULL returned within 10 seconds
 */
static gboolean
_stop_server_src_with_peer (const gchar *idl, gboolean blocking, const PeerFunc &peer)
{
  GstElement *pipeline, *src;
  PeerState state = { 0, 0 };
  gchar *str;
  gint port = 0;
  gboolean stopped;

  str = g_strdup_printf ("tensor_src_grpc name=grpc server=TRUE blocking=%s idl=%s host=localhost port=0 ! " STREAM_TENSOR_CAPS
                         " ! fakesink async=FALSE",
      blocking ? "TRUE" : "FALSE", idl);
  pipeline = gst_parse_launch (str, NULL);
  g_free (str);
  if (!pipeline) {
    ADD_FAILURE () << "the " << idl << " source pipeline did not build";
    return FALSE;
  }

  EXPECT_NE (gst_element_set_state (pipeline, GST_STATE_PLAYING), GST_STATE_CHANGE_FAILURE);
  src = gst_bin_get_by_name (GST_BIN (pipeline), "grpc");
  EXPECT_TRUE (_wait_for_caps (src));
  gst_object_unref (src);
  port = _grpc_port (pipeline);
  EXPECT_GT (port, 0);

  std::thread writer (peer, "localhost:" + std::to_string (port), &state);

  EXPECT_TRUE (_wait_for_peer (&state));
  /* let the server take the call */
  g_usleep (G_USEC_PER_SEC / 5);
  stopped = _set_null_in_time (pipeline);

  g_atomic_int_set (&state.release, 1);
  writer.join ();

  return stopped;
}

#endif /* ENABLE_PROTOBUF || ENABLE_FLATBUF */

#ifdef ENABLE_PROTOBUF
using PbTensors = nnstreamer::protobuf::Tensors;

/**
 * @brief Add a uint8 tensor holding @a data to a protobuf message.
 */
static void
_pb_add_tensor (PbTensors &msg, const std::string &data)
{
  nnstreamer::protobuf::Tensor *tensor = msg.add_tensor ();

  tensor->set_name ("test");
  tensor->set_type (nnstreamer::protobuf::Tensor::NNS_UINT8);
  tensor->add_dimension (data.size ());
  tensor->set_data (data);
}

/**
 * @brief Build a protobuf message that fits RECV_STATIC_CAPS.
 */
static PbTensors
_pb_valid_static (void)
{
  PbTensors msg;

  msg.set_num_tensor (2);
  _pb_add_tensor (msg, std::string (4, '\x01'));
  _pb_add_tensor (msg, std::string (2, '\x02'));
  return msg;
}

/**
 * @brief Send @a msgs over one client-streaming call of the protobuf service.
 */
static void
_pb_send (const std::string &address, const std::function<void ()> &wait,
    const std::vector<PbTensors> &msgs)
{
  auto stub = nnstreamer::protobuf::TensorService::NewStub (
      grpc::CreateChannel (address, grpc::InsecureChannelCredentials ()));
  grpc::ClientContext context;
  google::protobuf::Empty reply;
  auto writer = stub->SendTensors (&context, &reply);

  for (const PbTensors &msg : msgs)
    writer->Write (msg);
  writer->WritesDone ();
  wait ();
  writer->Finish ();
}

/**
 * @brief Run a protobuf receive test on @a caps: @a msgs, then wait for one buffer.
 */
static guint
_pb_recv (const std::string &caps, const std::vector<PbTensors> &msgs,
    std::vector<gsize> &sizes)
{
  return _run_recv_test (
      "protobuf", caps,
      [&] (const std::string &addr, const std::function<void ()> &wait) {
        _pb_send (addr, wait, msgs);
      },
      1, sizes);
}

/**
 * @brief tensor_src_grpc (protobuf) delivers a message that fits the caps.
 */
TEST (nnstreamerGrpc, recvProtobufStatic)
{
  std::vector<gsize> sizes;
  guint received = _pb_recv (RECV_STATIC_CAPS, { _pb_valid_static () }, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
  EXPECT_EQ (sizes[0], 4U);
  EXPECT_EQ (sizes[1], 2U);
}

/**
 * @brief tensor_src_grpc (protobuf) drops a message declaring more tensors than it carries.
 */
TEST (nnstreamerGrpc, recvProtobufMissingTensor_n)
{
  std::vector<gsize> sizes;
  PbTensors bad;

  bad.set_num_tensor (2);
  _pb_add_tensor (bad, std::string (4, '\x01'));

  guint received = _pb_recv (RECV_STATIC_CAPS, { bad, _pb_valid_static () }, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
}

/**
 * @brief tensor_src_grpc (protobuf) drops a message whose tensor count differs from the caps.
 */
TEST (nnstreamerGrpc, recvProtobufCountMismatch_n)
{
  std::vector<gsize> sizes;
  PbTensors bad;

  bad.set_num_tensor (1);
  _pb_add_tensor (bad, std::string (4, '\x01'));

  guint received = _pb_recv (RECV_STATIC_CAPS, { bad, _pb_valid_static () }, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
}

/**
 * @brief tensor_src_grpc (protobuf) drops a message whose data size differs from the caps.
 */
TEST (nnstreamerGrpc, recvProtobufSizeMismatch_n)
{
  std::vector<gsize> sizes;
  PbTensors bad;

  bad.set_num_tensor (2);
  _pb_add_tensor (bad, std::string (4, '\x01'));
  _pb_add_tensor (bad, std::string (3, '\x02'));

  guint received = _pb_recv (RECV_STATIC_CAPS, { bad, _pb_valid_static () }, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
  EXPECT_EQ (sizes[1], 2U);
}

/**
 * @brief Static caps of @a num one-byte uint8 tensors.
 */
static std::string
_many_tensors_caps (guint num)
{
  std::string dims, types;

  for (guint i = 0; i < num; i++) {
    dims += (i ? "." : "") + std::string ("1:1:1:1");
    types += (i ? "." : "") + std::string ("uint8");
  }

  return "other/tensors,num_tensors=" + std::to_string (num)
         + ",dimensions=" + dims + ",types=" + types + ",framerate=30/1";
}

/**
 * @brief Build a protobuf message of @a num one-byte tensors; tensor @a wrong gets two bytes.
 */
static PbTensors
_pb_many_tensors (guint num, guint wrong)
{
  PbTensors msg;

  msg.set_num_tensor (num);
  for (guint i = 0; i < num; i++)
    _pb_add_tensor (msg, std::string (i == wrong ? 2 : 1, '\x01'));
  return msg;
}

/**
 * @brief tensor_src_grpc (protobuf) delivers a message with more tensors than a buffer has memories.
 */
TEST (nnstreamerGrpc, recvProtobufExtraTensors)
{
  std::vector<gsize> sizes;
  guint received = _pb_recv (_many_tensors_caps (NNS_TENSOR_MEMORY_MAX + 4),
      { _pb_many_tensors (NNS_TENSOR_MEMORY_MAX + 4, G_MAXUINT) }, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), NNS_TENSOR_MEMORY_MAX + 4U);
  EXPECT_EQ (sizes[NNS_TENSOR_MEMORY_MAX + 3], 1U);
}

/**
 * @brief tensor_src_grpc (protobuf) drops a message whose extra tensor has the wrong size.
 */
TEST (nnstreamerGrpc, recvProtobufExtraTensorSizeMismatch_n)
{
  std::vector<gsize> sizes;
  guint received = _pb_recv (_many_tensors_caps (NNS_TENSOR_MEMORY_MAX + 4),
      { _pb_many_tensors (NNS_TENSOR_MEMORY_MAX + 4, NNS_TENSOR_MEMORY_MAX + 2),
          _pb_many_tensors (NNS_TENSOR_MEMORY_MAX + 4, G_MAXUINT) },
      sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), NNS_TENSOR_MEMORY_MAX + 4U);
  EXPECT_EQ (sizes[NNS_TENSOR_MEMORY_MAX + 2], 1U);
}

/**
 * @brief A non-blocking tensor_src_grpc (protobuf) client receives tensors and ends its call.
 */
TEST (nnstreamerGrpc, nonBlockingClientSrcProtobuf)
{
  EXPECT_GE (_run_nonblocking_test ("protobuf", TRUE), 2U);
}

/**
 * @brief A non-blocking tensor_sink_grpc (protobuf) client sends tensors and ends its call.
 */
TEST (nnstreamerGrpc, nonBlockingClientSinkProtobuf)
{
  EXPECT_GE (_run_nonblocking_test ("protobuf", FALSE), 2U);
}

/**
 * @brief A blocking tensor_sink_grpc (protobuf) server nobody connects to reaches NULL with buffers queued.
 */
TEST (nnstreamerGrpc, stopUndrainedServerSinkProtobuf_n)
{
  EXPECT_TRUE (_stop_undrained_sink ("protobuf", TRUE, TRUE));
}

/**
 * @brief A non-blocking tensor_sink_grpc (protobuf) server nobody connects to reaches NULL with buffers queued.
 */
TEST (nnstreamerGrpc, stopUndrainedAsyncServerSinkProtobuf_n)
{
  EXPECT_TRUE (_stop_undrained_sink ("protobuf", TRUE, FALSE));
}

/**
 * @brief A blocking tensor_sink_grpc (protobuf) client without a server reaches NULL with buffers queued.
 */
TEST (nnstreamerGrpc, stopUndrainedClientSinkProtobuf_n)
{
  EXPECT_TRUE (_stop_undrained_sink ("protobuf", FALSE, TRUE));
}

/**
 * @brief A non-blocking tensor_sink_grpc (protobuf) client without a server reaches NULL with buffers queued.
 */
TEST (nnstreamerGrpc, stopUndrainedAsyncClientSinkProtobuf_n)
{
  EXPECT_TRUE (_stop_undrained_sink ("protobuf", FALSE, FALSE));
}

/**
 * @brief Read the whole stream of a protobuf server, pausing before each message.
 */
static void
_pb_slow_recv (const std::string &address, PeerState *state)
{
  auto stub = nnstreamer::protobuf::TensorService::NewStub (
      grpc::CreateChannel (address, grpc::InsecureChannelCredentials ()));
  grpc::ClientContext context;
  google::protobuf::Empty empty;
  PbTensors msg;

  context.set_deadline (std::chrono::system_clock::now () + std::chrono::seconds (30));
  auto reader = stub->RecvTensors (&context, empty);

  g_usleep (PEER_READ_DELAY_US);
  while (reader->Read (&msg)) {
    g_atomic_int_inc (&state->count);
    g_usleep (PEER_READ_DELAY_US);
  }
  reader->Finish ();
}

/**
 * @brief Read one message of the stream of a protobuf server, then no more until released.
 */
static void
_pb_idle_recv (const std::string &address, PeerState *state)
{
  auto stub = nnstreamer::protobuf::TensorService::NewStub (
      grpc::CreateChannel (address, grpc::InsecureChannelCredentials ()));
  grpc::ClientContext context;
  google::protobuf::Empty empty;
  PbTensors msg;

  context.set_deadline (std::chrono::system_clock::now () + std::chrono::seconds (30));
  auto reader = stub->RecvTensors (&context, empty);

  if (reader->Read (&msg))
    g_atomic_int_inc (&state->count);
  _wait_for_release (state);

  context.TryCancel ();
  reader->Finish ();
}

/**
 * @brief Open a client-streaming call to a protobuf server and send nothing until released.
 */
static void
_pb_idle_send (const std::string &address, PeerState *state)
{
  auto stub = nnstreamer::protobuf::TensorService::NewStub (
      grpc::CreateChannel (address, grpc::InsecureChannelCredentials ()));
  grpc::ClientContext context;
  google::protobuf::Empty reply;

  context.set_deadline (std::chrono::system_clock::now () + std::chrono::seconds (30));
  auto writer = stub->SendTensors (&context, &reply);

  g_atomic_int_set (&state->count, 1);
  _wait_for_release (state);

  context.TryCancel ();
  writer->Finish ();
}

/**
 * @brief A protobuf server for a tensor_sink_grpc client: it reads the call slowly, or reads nothing of it.
 */
class PeerServiceProtobuf final : public nnstreamer::protobuf::TensorService::Service
{
  public:
  /** @brief Construct a server that reads every message slowly if @a reads, or none */
  PeerServiceProtobuf (gboolean reads, PeerState *state)
      : reads_ (reads), state_ (state)
  {
  }

  /** @brief Read the call, or hold it until it is cancelled or the test releases it */
  grpc::Status SendTensors (grpc::ServerContext *context,
      grpc::ServerReader<PbTensors> *reader, google::protobuf::Empty *reply) override
  {
    PbTensors msg;

    if (reads_) {
      while (reader->Read (&msg)) {
        g_atomic_int_inc (&state_->count);
        g_usleep (PEER_READ_DELAY_US);
      }
      return grpc::Status::OK;
    }

    g_atomic_int_set (&state_->count, 1);
    while (!context->IsCancelled () && !g_atomic_int_get (&state_->release))
      g_usleep (10000);

    return grpc::Status::OK;
  }

  private:
  gboolean reads_; /**< whether the call is read */
  PeerState *state_; /**< where the server reports */
};

/**
 * @brief A tensor_sink_grpc (protobuf) server that stops still hands every queued buffer to a peer reading slowly.
 */
TEST (nnstreamerGrpc, stopDrainsTakingPeerProtobuf)
{
  PeerState state = { 0, 0 };

  EXPECT_TRUE (_stop_server_sink_with_peer ("protobuf", TRUE, _pb_slow_recv, &state));
  EXPECT_EQ (g_atomic_int_get (&state.count), LARGE_FRAMES);
}

/**
 * @brief A blocking tensor_sink_grpc (protobuf) server reaches NULL while its peer stops reading.
 */
TEST (nnstreamerGrpc, stopIdlePeerServerSinkProtobuf_n)
{
  PeerState state = { 0, 0 };

  EXPECT_TRUE (_stop_server_sink_with_peer ("protobuf", TRUE, _pb_idle_recv, &state));
}

/**
 * @brief A non-blocking tensor_sink_grpc (protobuf) server reaches NULL while its peer stops reading.
 */
TEST (nnstreamerGrpc, stopIdlePeerAsyncServerSinkProtobuf_n)
{
  PeerState state = { 0, 0 };

  EXPECT_TRUE (_stop_server_sink_with_peer ("protobuf", FALSE, _pb_idle_recv, &state));
}

/**
 * @brief A blocking tensor_sink_grpc (protobuf) client that stops still hands every queued buffer to a server reading slowly.
 */
TEST (nnstreamerGrpc, stopDrainsToReadingServerProtobuf)
{
  PeerState state = { 0, 0 };
  PeerServiceProtobuf service (TRUE, &state);

  EXPECT_TRUE (_stop_client_sink_with_server ("protobuf", TRUE, &service, &state));
  EXPECT_EQ (g_atomic_int_get (&state.count), LARGE_FRAMES);
}

/**
 * @brief A blocking tensor_sink_grpc (protobuf) client that stops lets a slow server read, within the default stop-timeout, what the transport holds for it.
 */
TEST (nnstreamerGrpc, stopWaitsForSlowServerProtobuf)
{
  PeerState state = { 0, 0 };
  PeerServiceProtobuf service (TRUE, &state);

  EXPECT_EQ (_stop_client_sink_small_frames ("protobuf", "", &service, &state), SMALL_FRAMES);
}

/**
 * @brief A blocking tensor_sink_grpc (protobuf) client with a short stop-timeout drops what a slow server has not read by then.
 */
TEST (nnstreamerGrpc, stopTimeoutSlowServerProtobuf_n)
{
  PeerState state = { 0, 0 };
  PeerServiceProtobuf service (TRUE, &state);
  gint count = _stop_client_sink_small_frames (
      "protobuf", "stop-timeout=200", &service, &state);

  EXPECT_GT (count, 0);
  EXPECT_LT (count, SMALL_FRAMES);
}

/**
 * @brief A blocking tensor_sink_grpc (protobuf) client reaches NULL while its server reads nothing.
 */
TEST (nnstreamerGrpc, stopIdleServerClientSinkProtobuf_n)
{
  PeerState state = { 0, 0 };
  PeerServiceProtobuf service (FALSE, &state);

  EXPECT_TRUE (_stop_client_sink_with_server ("protobuf", TRUE, &service, &state));
}

/**
 * @brief A non-blocking tensor_sink_grpc (protobuf) client reaches NULL while its server reads nothing.
 */
TEST (nnstreamerGrpc, stopIdleServerAsyncClientSinkProtobuf_n)
{
  PeerState state = { 0, 0 };
  PeerServiceProtobuf service (FALSE, &state);

  EXPECT_TRUE (_stop_client_sink_with_server ("protobuf", FALSE, &service, &state));
}

/**
 * @brief A blocking tensor_src_grpc (protobuf) client reaches NULL while its server sends nothing.
 */
TEST (nnstreamerGrpc, stopIdleServerClientSrcProtobuf_n)
{
  EXPECT_TRUE (_stop_client_src_of_idle_server ("protobuf", TRUE));
}

/**
 * @brief A non-blocking tensor_src_grpc (protobuf) client reaches NULL while its server sends nothing.
 */
TEST (nnstreamerGrpc, stopIdleServerAsyncClientSrcProtobuf_n)
{
  EXPECT_TRUE (_stop_client_src_of_idle_server ("protobuf", FALSE));
}

/**
 * @brief A blocking tensor_src_grpc (protobuf) server reaches NULL while its client sends nothing.
 */
TEST (nnstreamerGrpc, stopIdlePeerServerSrcProtobuf_n)
{
  EXPECT_TRUE (_stop_server_src_with_peer ("protobuf", TRUE, _pb_idle_send));
}

/**
 * @brief A non-blocking tensor_src_grpc (protobuf) server reaches NULL while its client sends nothing.
 */
TEST (nnstreamerGrpc, stopIdlePeerAsyncServerSrcProtobuf_n)
{
  EXPECT_TRUE (_stop_server_src_with_peer ("protobuf", FALSE, _pb_idle_send));
}
#endif /* ENABLE_PROTOBUF */

#ifdef ENABLE_FLATBUF
using FbTensors = nnstreamer::flatbuf::Tensors;
using FbMessage = flatbuffers::grpc::Message<FbTensors>;

/**
 * @brief Build a flatbuf message with uint8 tensors of @a data_sizes bytes.
 * @param data_sizes A negative size leaves the data field of that tensor out; NULL leaves the tensor vector out.
 */
static FbMessage
_fb_build (gint num_tensor, const std::vector<gint> *data_sizes)
{
  flatbuffers::grpc::MessageBuilder builder;
  std::vector<flatbuffers::Offset<nnstreamer::flatbuf::Tensor>> tensors;
  nnstreamer::flatbuf::frame_rate fr (30, 1);
  guint32 dim[NNS_TENSOR_RANK_LIMIT] = { 0 };
  flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<nnstreamer::flatbuf::Tensor>>> vec;

  if (data_sizes) {
    for (gint size : *data_sizes) {
      std::vector<guint8> bytes (size > 0 ? size : 0, 1);
      auto name = builder.CreateString ("test");
      auto dims = builder.CreateVector (dim, NNS_TENSOR_RANK_LIMIT);
      flatbuffers::Offset<flatbuffers::Vector<guint8>> data;

      if (size >= 0)
        data = builder.CreateVector (bytes);

      tensors.push_back (nnstreamer::flatbuf::CreateTensor (builder, name,
          nnstreamer::flatbuf::Tensor_type_NNS_UINT8, dims, data));
    }
    vec = builder.CreateVector (tensors);
  }

  builder.Finish (nnstreamer::flatbuf::CreateTensors (builder, num_tensor, &fr, vec));
  return builder.ReleaseMessage<FbTensors> ();
}

/**
 * @brief Send @a msgs over one client-streaming call of the flatbuf service.
 */
static void
_fb_send (const std::string &address, const std::function<void ()> &wait,
    std::vector<FbMessage> &msgs)
{
  auto stub = nnstreamer::flatbuf::TensorService::NewStub (
      grpc::CreateChannel (address, grpc::InsecureChannelCredentials ()));
  grpc::ClientContext context;
  flatbuffers::grpc::Message<nnstreamer::flatbuf::Empty> reply;
  auto writer = stub->SendTensors (&context, &reply);

  for (FbMessage &msg : msgs)
    writer->Write (msg);
  writer->WritesDone ();
  /* Finish () of a flatbuf client-streaming call aborts, see SyncServiceImplFlatbuf::_client_thread (). */
  wait ();
}

/**
 * @brief Run a flatbuf receive test on RECV_STATIC_CAPS: the given message (if @a with_bad), then a valid one.
 */
static guint
_fb_recv (gboolean with_bad, gint num_tensor,
    const std::vector<gint> *data_sizes, std::vector<gsize> &sizes)
{
  const std::vector<gint> valid = { 4, 2 };

  return _run_recv_test (
      "flatbuf", RECV_STATIC_CAPS,
      [&] (const std::string &addr, const std::function<void ()> &wait) {
        std::vector<FbMessage> msgs;
        if (with_bad)
          msgs.push_back (_fb_build (num_tensor, data_sizes));
        msgs.push_back (_fb_build (2, &valid));
        _fb_send (addr, wait, msgs);
      },
      1, sizes);
}

/**
 * @brief tensor_src_grpc (flatbuf) delivers a message that fits the caps.
 */
TEST (nnstreamerGrpc, recvFlatbufStatic)
{
  std::vector<gsize> sizes;
  guint received = _fb_recv (FALSE, 0, NULL, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
  EXPECT_EQ (sizes[0], 4U);
  EXPECT_EQ (sizes[1], 2U);
}

/**
 * @brief tensor_src_grpc (flatbuf) drops a message without the tensor vector.
 */
TEST (nnstreamerGrpc, recvFlatbufNoTensorVector_n)
{
  std::vector<gsize> sizes;
  guint received = _fb_recv (TRUE, 2, NULL, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
}

/**
 * @brief tensor_src_grpc (flatbuf) drops a message declaring more tensors than it carries.
 */
TEST (nnstreamerGrpc, recvFlatbufMissingTensor_n)
{
  std::vector<gsize> sizes;
  const std::vector<gint> bad = { 4 };
  guint received = _fb_recv (TRUE, 2, &bad, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
}

/**
 * @brief tensor_src_grpc (flatbuf) drops a message declaring a negative tensor count.
 */
TEST (nnstreamerGrpc, recvFlatbufNegativeCount_n)
{
  std::vector<gsize> sizes;
  const std::vector<gint> bad = { 4, 2 };
  guint received = _fb_recv (TRUE, -1, &bad, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
}

/**
 * @brief tensor_src_grpc (flatbuf) drops a message whose tensor has no data field.
 */
TEST (nnstreamerGrpc, recvFlatbufNoData_n)
{
  std::vector<gsize> sizes;
  const std::vector<gint> bad = { 4, -1 };
  guint received = _fb_recv (TRUE, 2, &bad, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
}

/**
 * @brief tensor_src_grpc (flatbuf) drops a message whose data size differs from the caps.
 */
TEST (nnstreamerGrpc, recvFlatbufSizeMismatch_n)
{
  std::vector<gsize> sizes;
  const std::vector<gint> bad = { 4, 3 };
  guint received = _fb_recv (TRUE, 2, &bad, sizes);

  EXPECT_EQ (received, 1U);
  ASSERT_EQ (sizes.size (), 2U);
  EXPECT_EQ (sizes[1], 2U);
}

/**
 * @brief A non-blocking tensor_src_grpc (flatbuf) client receives tensors and ends its call.
 */
TEST (nnstreamerGrpc, nonBlockingClientSrcFlatbuf)
{
  EXPECT_GE (_run_nonblocking_test ("flatbuf", TRUE), 2U);
}

/**
 * @brief A non-blocking tensor_sink_grpc (flatbuf) client sends tensors and ends its call.
 */
TEST (nnstreamerGrpc, nonBlockingClientSinkFlatbuf)
{
  EXPECT_GE (_run_nonblocking_test ("flatbuf", FALSE), 2U);
}

/**
 * @brief A blocking tensor_sink_grpc (flatbuf) server nobody connects to reaches NULL with buffers queued.
 */
TEST (nnstreamerGrpc, stopUndrainedServerSinkFlatbuf_n)
{
  EXPECT_TRUE (_stop_undrained_sink ("flatbuf", TRUE, TRUE));
}

/**
 * @brief A non-blocking tensor_sink_grpc (flatbuf) server nobody connects to reaches NULL with buffers queued.
 */
TEST (nnstreamerGrpc, stopUndrainedAsyncServerSinkFlatbuf_n)
{
  EXPECT_TRUE (_stop_undrained_sink ("flatbuf", TRUE, FALSE));
}

/**
 * @brief A blocking tensor_sink_grpc (flatbuf) client without a server reaches NULL with buffers queued.
 */
TEST (nnstreamerGrpc, stopUndrainedClientSinkFlatbuf_n)
{
  EXPECT_TRUE (_stop_undrained_sink ("flatbuf", FALSE, TRUE));
}

/**
 * @brief A non-blocking tensor_sink_grpc (flatbuf) client without a server reaches NULL with buffers queued.
 */
TEST (nnstreamerGrpc, stopUndrainedAsyncClientSinkFlatbuf_n)
{
  EXPECT_TRUE (_stop_undrained_sink ("flatbuf", FALSE, FALSE));
}

/**
 * @brief Build the empty request of a flatbuf server-streaming call.
 */
static flatbuffers::grpc::Message<nnstreamer::flatbuf::Empty>
_fb_empty (void)
{
  flatbuffers::grpc::MessageBuilder builder;

  builder.Finish (nnstreamer::flatbuf::CreateEmpty (builder));
  return builder.ReleaseMessage<nnstreamer::flatbuf::Empty> ();
}

/**
 * @brief Read the whole stream of a flatbuf server, pausing before each message.
 */
static void
_fb_slow_recv (const std::string &address, PeerState *state)
{
  auto stub = nnstreamer::flatbuf::TensorService::NewStub (
      grpc::CreateChannel (address, grpc::InsecureChannelCredentials ()));
  grpc::ClientContext context;
  FbMessage msg;

  context.set_deadline (std::chrono::system_clock::now () + std::chrono::seconds (30));
  auto reader = stub->RecvTensors (&context, _fb_empty ());

  g_usleep (PEER_READ_DELAY_US);
  while (reader->Read (&msg)) {
    g_atomic_int_inc (&state->count);
    g_usleep (PEER_READ_DELAY_US);
  }
  reader->Finish ();
}

/**
 * @brief Read one message of the stream of a flatbuf server, then no more until released.
 */
static void
_fb_idle_recv (const std::string &address, PeerState *state)
{
  auto stub = nnstreamer::flatbuf::TensorService::NewStub (
      grpc::CreateChannel (address, grpc::InsecureChannelCredentials ()));
  grpc::ClientContext context;
  FbMessage msg;

  context.set_deadline (std::chrono::system_clock::now () + std::chrono::seconds (30));
  auto reader = stub->RecvTensors (&context, _fb_empty ());

  if (reader->Read (&msg))
    g_atomic_int_inc (&state->count);
  _wait_for_release (state);

  context.TryCancel ();
  reader->Finish ();
}

/**
 * @brief Open a client-streaming call to a flatbuf server and send nothing until released.
 */
static void
_fb_idle_send (const std::string &address, PeerState *state)
{
  auto stub = nnstreamer::flatbuf::TensorService::NewStub (
      grpc::CreateChannel (address, grpc::InsecureChannelCredentials ()));
  grpc::ClientContext context;
  flatbuffers::grpc::Message<nnstreamer::flatbuf::Empty> reply;

  context.set_deadline (std::chrono::system_clock::now () + std::chrono::seconds (30));
  auto writer = stub->SendTensors (&context, &reply);

  g_atomic_int_set (&state->count, 1);
  _wait_for_release (state);

  /* Finish () of a flatbuf client-streaming call aborts, see SyncServiceImplFlatbuf::_client_thread (). */
  context.TryCancel ();
}

/**
 * @brief A flatbuf server that takes the call of a tensor_sink_grpc client but reads nothing of it.
 */
class IdleServiceFlatbuf final : public nnstreamer::flatbuf::TensorService::Service
{
  public:
  /** @brief Construct a server reporting in @a state */
  IdleServiceFlatbuf (PeerState *state) : state_ (state)
  {
  }

  /** @brief Hold the call until it is cancelled or the test releases it */
  grpc::Status SendTensors (grpc::ServerContext *context,
      grpc::ServerReader<FbMessage> *reader,
      flatbuffers::grpc::Message<nnstreamer::flatbuf::Empty> *reply) override
  {
    g_atomic_int_set (&state_->count, 1);
    while (!context->IsCancelled () && !g_atomic_int_get (&state_->release))
      g_usleep (10000);

    return grpc::Status::OK;
  }

  private:
  PeerState *state_; /**< where the server reports */
};

/**
 * @brief A tensor_sink_grpc (flatbuf) server that stops still hands every queued buffer to a peer reading slowly.
 */
TEST (nnstreamerGrpc, stopDrainsTakingPeerFlatbuf)
{
  PeerState state = { 0, 0 };

  EXPECT_TRUE (_stop_server_sink_with_peer ("flatbuf", TRUE, _fb_slow_recv, &state));
  EXPECT_EQ (g_atomic_int_get (&state.count), LARGE_FRAMES);
}

/**
 * @brief A blocking tensor_sink_grpc (flatbuf) server reaches NULL while its peer stops reading.
 */
TEST (nnstreamerGrpc, stopIdlePeerServerSinkFlatbuf_n)
{
  PeerState state = { 0, 0 };

  EXPECT_TRUE (_stop_server_sink_with_peer ("flatbuf", TRUE, _fb_idle_recv, &state));
}

/**
 * @brief A non-blocking tensor_sink_grpc (flatbuf) server reaches NULL while its peer stops reading.
 */
TEST (nnstreamerGrpc, stopIdlePeerAsyncServerSinkFlatbuf_n)
{
  PeerState state = { 0, 0 };

  EXPECT_TRUE (_stop_server_sink_with_peer ("flatbuf", FALSE, _fb_idle_recv, &state));
}

/**
 * @brief A blocking tensor_sink_grpc (flatbuf) client reaches NULL while its server reads nothing.
 */
TEST (nnstreamerGrpc, stopIdleServerClientSinkFlatbuf_n)
{
  PeerState state = { 0, 0 };
  IdleServiceFlatbuf service (&state);

  EXPECT_TRUE (_stop_client_sink_with_server ("flatbuf", TRUE, &service, &state));
}

/**
 * @brief A non-blocking tensor_sink_grpc (flatbuf) client reaches NULL while its server reads nothing.
 */
TEST (nnstreamerGrpc, stopIdleServerAsyncClientSinkFlatbuf_n)
{
  PeerState state = { 0, 0 };
  IdleServiceFlatbuf service (&state);

  EXPECT_TRUE (_stop_client_sink_with_server ("flatbuf", FALSE, &service, &state));
}

/**
 * @brief A blocking tensor_src_grpc (flatbuf) client reaches NULL while its server sends nothing.
 */
TEST (nnstreamerGrpc, stopIdleServerClientSrcFlatbuf_n)
{
  EXPECT_TRUE (_stop_client_src_of_idle_server ("flatbuf", TRUE));
}

/**
 * @brief A non-blocking tensor_src_grpc (flatbuf) client reaches NULL while its server sends nothing.
 */
TEST (nnstreamerGrpc, stopIdleServerAsyncClientSrcFlatbuf_n)
{
  EXPECT_TRUE (_stop_client_src_of_idle_server ("flatbuf", FALSE));
}

/**
 * @brief A blocking tensor_src_grpc (flatbuf) server reaches NULL while its client sends nothing.
 */
TEST (nnstreamerGrpc, stopIdlePeerServerSrcFlatbuf_n)
{
  EXPECT_TRUE (_stop_server_src_with_peer ("flatbuf", TRUE, _fb_idle_send));
}

/**
 * @brief A non-blocking tensor_src_grpc (flatbuf) server reaches NULL while its client sends nothing.
 */
TEST (nnstreamerGrpc, stopIdlePeerAsyncServerSrcFlatbuf_n)
{
  EXPECT_TRUE (_stop_server_src_with_peer ("flatbuf", FALSE, _fb_idle_send));
}
#endif /* ENABLE_FLATBUF */

/**
 * @brief gtest main
 */
int
main (int argc, char **argv)
{
  int result = -1;

  try {
    testing::InitGoogleTest (&argc, argv);
  } catch (...) {
    g_warning ("catch 'testing::internal::<unnamed>::ClassUniqueToAlwaysTrue'");
  }

  gst_init (&argc, &argv);

#if defined(ENABLE_PROTOBUF) || defined(ENABLE_FLATBUF)
  /* keep gRPC initialized across the cases; its shutdown waits for the transport to wind down */
  grpc_init ();
#endif

  try {
    result = RUN_ALL_TESTS ();
  } catch (...) {
    g_warning ("catch `testing::internal::GoogleTestFailureException`");
  }

  return result;
}
