/* SPDX-License-Identifier: LGPL-2.1-only */
/**
 * @file        unittest_converter_serialized.cc
 * @date        15 Sep 2026
 * @brief       Unit test for the flatbuf/flexbuf/protobuf tensor_converter
 *              subplugins with peer-controlled (possibly malformed) input.
 * @see         https://github.com/nnstreamer/nnstreamer
 * @author      MyungJoo Ham <myungjoo.ham@samsung.com>
 * @bug         No known bugs
 */

#include <gtest/gtest.h>
#include <cstring>
#include <glib.h>
#include <gst/check/gstharness.h>
#include <gst/gst.h>
#include <nnstreamer_plugin_api.h>
#include <nnstreamer_plugin_api_converter.h>
#include <nnstreamer_plugin_api_decoder.h>
#include <nnstreamer_plugin_api_util.h>
#include <string>
#include <tensor_typedef.h>
#include <unittest_util.h>
#include <vector>

#ifdef ENABLE_FLATBUF
#include <flatbuffers/flexbuffers.h>
#include <nnstreamer_flatbuf.h>
#include <nnstreamer_generated.h> /* Generated by `flatc`. */
using namespace nnstreamer::flatbuf;
#endif /* ENABLE_FLATBUF */

#ifdef ENABLE_PROTOBUF
#include <nnstreamer_protobuf.h>
#include "nnstreamer.pb.h" /* Generated by `protoc` */
namespace nns_pb = nnstreamer::protobuf;
#endif /* ENABLE_PROTOBUF */

/**
 * @brief Copy @a size bytes of @a data into a newly g_malloc()'d buffer.
 * @note This avoids depending on g_memdup2()'s availability across GLib versions.
 */
static gpointer
dup_bytes (const void *data, gsize size)
{
  gpointer copy = g_malloc (size ? size : 1);

  if (size)
    memcpy (copy, data, size);

  return copy;
}

/**
 * @brief Wrap a heap copy of [data, size) into a newly allocated, single-memory GstBuffer.
 */
static GstBuffer *
wrap_as_gst_buffer (const void *data, gsize size)
{
  gpointer copy = dup_bytes (data, size);
  GstMemory *mem
      = gst_memory_new_wrapped ((GstMemoryFlags) 0, copy, size, 0, size, copy, g_free);
  GstBuffer *buf = gst_buffer_new ();

  gst_buffer_append_memory (buf, mem);
  return buf;
}

/**
 * @brief The fixed header size (in bytes) that a flexible-format tensor carries in front of its data.
 */
static gsize
meta_header_size (void)
{
  GstTensorMetaInfo meta;

  gst_tensor_meta_info_init (&meta);
  return gst_tensor_meta_info_get_header_size (&meta);
}

/**
 * @brief Build a valid flexible-format tensor payload: a GstTensorMetaInfo header followed by @a payload.
 */
static std::vector<guint8>
build_flexible_bytes (tensor_type type, const gchar *dim_str, const std::vector<guint8> &payload)
{
  GstTensorInfo info;
  GstTensorMetaInfo meta;
  gsize header_size;
  std::vector<guint8> out;

  gst_tensor_info_init (&info);
  info.type = type;
  gst_tensor_parse_dimension (dim_str, info.dimension);
  gst_tensor_info_convert_to_meta (&info, &meta);

  header_size = gst_tensor_meta_info_get_header_size (&meta);
  out.resize (header_size + payload.size ());
  gst_tensor_meta_info_update_header (&meta, out.data ());
  if (!payload.empty ())
    memcpy (out.data () + header_size, payload.data (), payload.size ());

  gst_tensor_info_free (&info);
  return out;
}

/**
 * @brief Plan for one tensor entry of a hand-built serialized message.
 * @note Not every knob applies to every format; see the per-format builders below.
 */
struct TestTensor {
  const gchar *name = nullptr; /**< nullptr: flatbuf omits the field; flexbuf/protobuf send "" */
  gint32 type = _NNS_UINT8;
  std::vector<guint32> dimension; /**< fewer than NNS_TENSOR_RANK_LIMIT entries is allowed */
  std::vector<guint8> data;
  gboolean has_data = TRUE; /**< flatbuf only: FALSE omits the data field entirely */
  gboolean data_is_blob = TRUE; /**< flexbuf only: FALSE writes tensor[3] as an Int, not a Blob */
};

/**
 * @brief Build a tensor with the given type/dimension/data, defaulting dimension to 16 ranks.
 */
static TestTensor
make_tensor (const gchar *name, tensor_type type, guint32 dim0,
    const std::vector<guint8> &data)
{
  TestTensor t;

  t.name = name;
  t.type = type;
  t.dimension = std::vector<guint32> (NNS_TENSOR_RANK_LIMIT, 1);
  t.dimension[0] = dim0;
  t.data = data;
  return t;
}

#ifdef ENABLE_FLATBUF
/**
 * @brief Serialize a flatbuffers Tensors message, with knobs to build malformed messages.
 * @param num_tensor value written into the `num_tensor` field (need not match @a tensors.size ())
 * @param has_fr FALSE omits the `fr` field entirely
 * @param has_tensor_field FALSE omits the `tensor` field entirely
 */
static std::vector<guint8>
build_flatbuf (gint32 num_tensor, gboolean has_fr, gboolean has_tensor_field,
    gint32 rate_n, gint32 rate_d, gint32 format, const std::vector<TestTensor> &tensors)
{
  flatbuffers::FlatBufferBuilder builder;
  std::vector<flatbuffers::Offset<Tensor>> tensor_vector;

  for (const auto &t : tensors) {
    flatbuffers::Offset<flatbuffers::String> name_off = 0;
    flatbuffers::Offset<flatbuffers::Vector<uint32_t>> dim_off = 0;
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data_off = 0;

    if (t.name)
      name_off = builder.CreateString (t.name);
    if (!t.dimension.empty ())
      dim_off = builder.CreateVector (t.dimension);
    if (t.has_data)
      data_off = builder.CreateVector (t.data);

    tensor_vector.push_back (
        CreateTensor (builder, name_off, (Tensor_type) t.type, dim_off, data_off));
  }

  flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Tensor>>> tensor_vec_off = 0;
  if (has_tensor_field)
    tensor_vec_off = builder.CreateVector (tensor_vector);

  frame_rate fr (rate_n, rate_d);
  flatbuffers::Offset<Tensors> tensors_off = CreateTensors (builder, num_tensor,
      has_fr ? &fr : nullptr, tensor_vec_off, (Tensor_format) format);

  builder.Finish (tensors_off);

  const uint8_t *ptr = builder.GetBufferPointer ();
  return std::vector<guint8> (ptr, ptr + builder.GetSize ());
}

/**
 * @brief Serialize a flexbuffers message, with knobs to build malformed messages.
 * @param omit_key_index if >= 0, the `tensor_<index>` key is not written at all
 */
static std::vector<guint8>
build_flexbuf (gint32 num_tensors, gint32 rate_n, gint32 rate_d, gint32 format,
    const std::vector<TestTensor> &tensors, gint omit_key_index = -1)
{
  flexbuffers::Builder fbb;
  guint n = (guint) tensors.size ();

  fbb.Map ([&] () {
    fbb.UInt ("num_tensors", (guint32) num_tensors);
    fbb.Int ("rate_n", rate_n);
    fbb.Int ("rate_d", rate_d);
    fbb.Int ("format", format);

    for (guint i = 0; i < n; i++) {
      if ((gint) i == omit_key_index)
        continue;

      gchar *key = g_strdup_printf ("tensor_%u", i);
      const TestTensor &t = tensors[i];

      fbb.Vector (key, [&] () {
        fbb += (t.name ? t.name : "");
        fbb += t.type;
        if (!t.dimension.empty ())
          fbb.Vector (t.dimension.data (), t.dimension.size ());
        if (t.data_is_blob) {
          const guint8 dummy = 0;
          const void *ptr = t.data.empty () ? (const void *) &dummy :
                                              (const void *) t.data.data ();
          fbb.Blob (ptr, t.data.size ());
        } else {
          /* Deliberately wrong type: an Int where the converter expects a Blob. */
          fbb += 12345;
        }
      });
      g_free (key);
    }
  });

  fbb.Finish ();
  const std::vector<uint8_t> &buf = fbb.GetBuffer ();
  return std::vector<guint8> (buf.begin (), buf.end ());
}
#endif /* ENABLE_FLATBUF */

#ifdef ENABLE_PROTOBUF
/**
 * @brief Serialize a protobuf Tensors message, with knobs to build malformed messages.
 * @param num_tensor value written into the `num_tensor` field (need not match @a tensors.size ())
 */
static std::string
build_protobuf (guint32 num_tensor, gint32 rate_n, gint32 rate_d, gint32 format,
    const std::vector<TestTensor> &tensors)
{
  nns_pb::Tensors msg;
  nns_pb::Tensors::frame_rate *fr;
  std::string out;

  msg.set_num_tensor (num_tensor);
  msg.set_format ((nns_pb::Tensors::Tensor_format) format);

  fr = msg.mutable_fr ();
  fr->set_rate_n (rate_n);
  fr->set_rate_d (rate_d);

  for (const auto &t : tensors) {
    nns_pb::Tensor *tensor = msg.add_tensor ();

    if (t.name)
      tensor->set_name (t.name);
    tensor->set_type ((nns_pb::Tensor::Tensor_type) t.type);
    for (guint32 d : t.dimension)
      tensor->add_dimension (d);
    if (!t.data.empty ())
      tensor->set_data (t.data.data (), t.data.size ());
  }

  msg.SerializeToString (&out);
  return out;
}
#endif /* ENABLE_PROTOBUF */

/**
 * @brief The list of "flatbuf" / "flexbuf" / "protobuf" mode names that are compiled into this build.
 */
static std::vector<std::string>
available_modes (void)
{
  std::vector<std::string> modes;

#ifdef ENABLE_FLATBUF
  modes.push_back ("flatbuf");
  modes.push_back ("flexbuf");
#endif
#ifdef ENABLE_PROTOBUF
  modes.push_back ("protobuf");
#endif

  return modes;
}

/**
 * @brief Serialize a Tensors message for @a mode, dispatching to the matching format-specific builder.
 * @return An empty vector if @a mode is not compiled into this build.
 */
static std::vector<guint8>
build_serialized_message (const std::string &mode, gint32 num_tensor, gint32 rate_n,
    gint32 rate_d, gint32 format, const std::vector<TestTensor> &tensors)
{
#ifdef ENABLE_FLATBUF
  if (mode == "flatbuf")
    return build_flatbuf (num_tensor, TRUE, TRUE, rate_n, rate_d, format, tensors);
  if (mode == "flexbuf")
    return build_flexbuf (num_tensor, rate_n, rate_d, format, tensors);
#endif
#ifdef ENABLE_PROTOBUF
  if (mode == "protobuf") {
    std::string s = build_protobuf ((guint32) num_tensor, rate_n, rate_d, format, tensors);
    return std::vector<guint8> (s.begin (), s.end ());
  }
#endif
  return std::vector<guint8> ();
}

/**
 * @brief TRUE if @a mode's converter is known to verify its input buffer before parsing it.
 * @note flxc_convert only calls flexbuffers::VerifyBuffer () with flatbuffers >= 2.0.6;
 *       with an older flatbuffers, a "not a valid message at all" case is not guaranteed
 *       to be rejected (or even safe to parse), so such cases skip flexbuf below.
 */
static gboolean
mode_verifies_untrusted_bytes (const std::string &mode)
{
  if (mode != "flexbuf")
    return TRUE;

#ifdef ENABLE_FLATBUF
#if FLATBUFFERS_VERSION_MAJOR > 2 \
    || (FLATBUFFERS_VERSION_MAJOR == 2 && FLATBUFFERS_VERSION_REVISION >= 6)
  return TRUE;
#else
  return FALSE;
#endif
#else
  return FALSE;
#endif
}

/**
 * @brief The fixed caps string that selects a serialized-tensor converter sub-plugin by mimetype.
 */
static const gchar *
mode_caps (const std::string &mode)
{
  if (mode == "flatbuf")
    return "other/flatbuf-tensor,framerate=(fraction)0/1";
  if (mode == "flexbuf")
    return "other/flexbuf";
  if (mode == "protobuf")
    return "other/protobuf-tensor,framerate=(fraction)0/1";

  return NULL;
}

/**
 * @brief Positive: a well-formed static message with 2 tensors (one named, one unnamed) converts.
 */
TEST (testConverterSerialized, staticTwoTensors)
{
  for (const auto &mode : available_modes ()) {
    const NNStreamerExternalConverter *conv = nnstreamer_converter_find (mode.c_str ());
    ASSERT_TRUE (conv) << mode;

    std::vector<TestTensor> tensors;
    tensors.push_back (make_tensor (nullptr, _NNS_UINT8, 12, std::vector<guint8> ()));
    for (guint8 i = 0; i < 12; i++)
      tensors[0].data.push_back (i);
    tensors.push_back (make_tensor ("second", _NNS_UINT8, 4, std::vector<guint8> ()));
    for (guint8 i = 0; i < 4; i++)
      tensors[1].data.push_back (100 + i);

    std::vector<guint8> bytes = build_serialized_message (
        mode, 2, 30, 1, _NNS_TENSOR_FORMAT_STATIC, tensors);
    ASSERT_FALSE (bytes.empty ()) << mode;

    GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
    GstTensorsConfig config;

    gst_tensors_config_init (&config);

    GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
    ASSERT_TRUE (out_buf != NULL) << mode;

    EXPECT_EQ (config.info.num_tensors, 2U) << mode;
    EXPECT_EQ (config.info.info[0].type, _NNS_UINT8) << mode;
    EXPECT_EQ (config.info.info[1].type, _NNS_UINT8) << mode;
    EXPECT_TRUE (config.info.info[0].name == NULL) << mode;
    EXPECT_STREQ ("second", config.info.info[1].name) << mode;
    EXPECT_EQ (config.info.info[0].dimension[0], 12U) << mode;
    EXPECT_EQ (config.info.info[1].dimension[0], 4U) << mode;
    ASSERT_EQ (gst_buffer_n_memory (out_buf), 2U) << mode;

    for (guint i = 0; i < 2; i++) {
      GstMemory *mem = gst_buffer_peek_memory (out_buf, i);
      GstMapInfo map_info;

      ASSERT_TRUE (gst_memory_map (mem, &map_info, GST_MAP_READ)) << mode;
      ASSERT_EQ (map_info.size, tensors[i].data.size ()) << mode;
      for (gsize j = 0; j < tensors[i].data.size (); j++)
        EXPECT_EQ (map_info.data[j], tensors[i].data[j]) << mode << " " << i << " " << j;
      gst_memory_unmap (mem, &map_info);
    }

    gst_tensors_config_free (&config);
    gst_buffer_unref (in_buf);
    gst_buffer_unref (out_buf);
  }
}

/**
 * @brief Positive: a round trip of more than NNS_TENSOR_MEMORY_MAX tensors through the decoder
 * then the converter, exercising the extra-tensor memory path that the new checks must not break.
 */
TEST (testConverterSerialized, roundTripManyTensors)
{
  const guint num = 18;

  for (const auto &mode : available_modes ()) {
    const GstTensorDecoderDef *dec = nnstreamer_decoder_find (mode.c_str ());
    const NNStreamerExternalConverter *conv = nnstreamer_converter_find (mode.c_str ());
    ASSERT_TRUE (dec) << mode;
    ASSERT_TRUE (conv) << mode;

    GstTensorsConfig config, check_config;
    GstTensorMemory input[num];
    GstTensorInfo *_info;

    gst_tensors_config_init (&config);
    gst_tensors_config_init (&check_config);
    config.rate_n = 0;
    config.rate_d = 1;
    config.info.num_tensors = num;
    config.info.format = _NNS_TENSOR_FORMAT_STATIC;

    for (guint i = 0; i < num; i++) {
      _info = gst_tensors_info_get_nth_info (&config.info, i);
      _info->type = _NNS_UINT8;
      gst_tensor_parse_dimension ("1:1:1:1", _info->dimension);

      input[i].size = 1;
      input[i].data = g_malloc (1);
      ((guint8 *) input[i].data)[0] = (guint8) (i + 1);
    }

    GstBuffer *dec_out_buf = gst_buffer_new ();
    EXPECT_EQ (GST_FLOW_OK, dec->decode (NULL, &config, input, dec_out_buf)) << mode;

    for (guint i = 0; i < num; i++)
      g_free (input[i].data);

    GstBuffer *conv_out_buf = conv->convert (dec_out_buf, &check_config, NULL);
    ASSERT_TRUE (conv_out_buf != NULL) << mode;
    EXPECT_EQ (check_config.info.num_tensors, num) << mode;

    for (guint i = 0; i < num; i++) {
      GstMemory *mem = gst_tensor_buffer_get_nth_memory (conv_out_buf, i);
      GstMapInfo map_info;

      ASSERT_TRUE (mem != NULL) << mode << " " << i;
      ASSERT_TRUE (gst_memory_map (mem, &map_info, GST_MAP_READ)) << mode;
      ASSERT_EQ (map_info.size, 1U) << mode;
      EXPECT_EQ (map_info.data[0], (guint8) (i + 1)) << mode << " " << i;
      gst_memory_unmap (mem, &map_info);
      gst_memory_unref (mem);
    }

    gst_tensors_config_free (&config);
    gst_tensors_config_free (&check_config);
    gst_buffer_unref (dec_out_buf);
    gst_buffer_unref (conv_out_buf);
  }
}

/**
 * @brief Positive: a round trip of a flexible-format stream through the decoder then the converter.
 */
TEST (testConverterSerialized, roundTripFlexible)
{
  for (const auto &mode : available_modes ()) {
    const GstTensorDecoderDef *dec = nnstreamer_decoder_find (mode.c_str ());
    const NNStreamerExternalConverter *conv = nnstreamer_converter_find (mode.c_str ());
    ASSERT_TRUE (dec) << mode;
    ASSERT_TRUE (conv) << mode;

    std::vector<guint8> payload0 = { 1, 2, 3, 4 };
    std::vector<guint8> payload1 = { 5, 6, 7, 8, 9, 10 };
    std::vector<guint8> bytes0 = build_flexible_bytes (_NNS_UINT8, "4:1:1:1", payload0);
    std::vector<guint8> bytes1 = build_flexible_bytes (_NNS_UINT8, "6:1:1:1", payload1);
    GstTensorsConfig config, check_config;
    GstTensorMemory input[2];

    gst_tensors_config_init (&config);
    gst_tensors_config_init (&check_config);
    config.rate_n = 0;
    config.rate_d = 1;
    config.info.num_tensors = 2;
    config.info.format = _NNS_TENSOR_FORMAT_FLEXIBLE;

    input[0].size = bytes0.size ();
    input[0].data = dup_bytes (bytes0.data (), bytes0.size ());
    input[1].size = bytes1.size ();
    input[1].data = dup_bytes (bytes1.data (), bytes1.size ());

    GstBuffer *dec_out_buf = gst_buffer_new ();
    EXPECT_EQ (GST_FLOW_OK, dec->decode (NULL, &config, input, dec_out_buf)) << mode;

    g_free (input[0].data);
    g_free (input[1].data);

    GstBuffer *conv_out_buf = conv->convert (dec_out_buf, &check_config, NULL);
    ASSERT_TRUE (conv_out_buf != NULL) << mode;
    ASSERT_EQ (check_config.info.num_tensors, 2U) << mode;
    EXPECT_TRUE (gst_tensors_config_is_flexible (&check_config)) << mode;
    ASSERT_EQ (gst_buffer_n_memory (conv_out_buf), 2U) << mode;

    const std::vector<guint8> *expected[2] = { &bytes0, &bytes1 };
    for (guint i = 0; i < 2; i++) {
      GstMemory *mem = gst_buffer_peek_memory (conv_out_buf, i);
      GstMapInfo map_info;

      ASSERT_TRUE (gst_memory_map (mem, &map_info, GST_MAP_READ)) << mode;
      ASSERT_EQ (map_info.size, expected[i]->size ()) << mode;
      EXPECT_EQ (0, memcmp (map_info.data, expected[i]->data (), map_info.size)) << mode;
      gst_memory_unmap (mem, &map_info);
    }

    gst_tensors_config_free (&config);
    gst_tensors_config_free (&check_config);
    gst_buffer_unref (dec_out_buf);
    gst_buffer_unref (conv_out_buf);
  }
}

/**
 * @brief Negative: a static tensor whose carried data size does not match type * dimension.
 */
TEST (testConverterSerialized, dataSizeMismatch_n)
{
  for (const auto &mode : available_modes ()) {
    for (int delta : { -1, 1 }) {
      const NNStreamerExternalConverter *conv
          = nnstreamer_converter_find (mode.c_str ());
      ASSERT_TRUE (conv) << mode;

      TestTensor t = make_tensor ("t", _NNS_UINT8, 4, std::vector<guint8> ());
      gsize n = (gsize) (4 + delta);
      for (gsize i = 0; i < n; i++)
        t.data.push_back ((guint8) i);

      std::vector<guint8> bytes = build_serialized_message (
          mode, 1, 30, 1, _NNS_TENSOR_FORMAT_STATIC, { t });
      ASSERT_FALSE (bytes.empty ()) << mode;

      GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
      GstTensorsConfig config;

      gst_tensors_config_init (&config);

      GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
      EXPECT_TRUE (out_buf == NULL) << mode << " delta=" << delta;

      if (out_buf)
        gst_buffer_unref (out_buf);
      gst_tensors_config_free (&config);
      gst_buffer_unref (in_buf);
    }
  }
}

/**
 * @brief Negative: a tensor whose declared type is out of the valid range.
 */
TEST (testConverterSerialized, invalidTensorType_n)
{
  std::vector<gint32> bad_types = { 99, (gint32) _NNS_END };

  for (const auto &mode : available_modes ()) {
    for (gint32 type : bad_types) {
      const NNStreamerExternalConverter *conv
          = nnstreamer_converter_find (mode.c_str ());
      ASSERT_TRUE (conv) << mode;

      TestTensor t = make_tensor ("t", (tensor_type) type, 4, { 0, 0, 0, 0 });

      std::vector<guint8> bytes = build_serialized_message (
          mode, 1, 30, 1, _NNS_TENSOR_FORMAT_STATIC, { t });
      ASSERT_FALSE (bytes.empty ()) << mode;

      GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
      GstTensorsConfig config;

      gst_tensors_config_init (&config);

      GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
      EXPECT_TRUE (out_buf == NULL) << mode << " type=" << type;

      if (out_buf)
        gst_buffer_unref (out_buf);
      gst_tensors_config_free (&config);
      gst_buffer_unref (in_buf);
    }
  }
}

/**
 * @brief Negative: the stream declares a tensor_format the framework does not know.
 */
TEST (testConverterSerialized, unknownFormat_n)
{
  for (const auto &mode : available_modes ()) {
    const NNStreamerExternalConverter *conv = nnstreamer_converter_find (mode.c_str ());
    ASSERT_TRUE (conv) << mode;

    TestTensor t = make_tensor ("t", _NNS_UINT8, 4, { 0, 0, 0, 0 });

    std::vector<guint8> bytes = build_serialized_message (mode, 1, 30, 1, 7, { t });
    ASSERT_FALSE (bytes.empty ()) << mode;

    GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
    GstTensorsConfig config;

    gst_tensors_config_init (&config);

    GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
    EXPECT_TRUE (out_buf == NULL) << mode;

    if (out_buf)
      gst_buffer_unref (out_buf);
    gst_tensors_config_free (&config);
    gst_buffer_unref (in_buf);
  }
}

/**
 * @brief Negative: the stream declares no tensor at all.
 * @note No per-tensor check runs for such a message, and the empty buffer it
 * yields cannot be described by fixed caps.
 */
TEST (testConverterSerialized, zeroTensors_n)
{
  for (const auto &mode : available_modes ()) {
    const NNStreamerExternalConverter *conv = nnstreamer_converter_find (mode.c_str ());
    ASSERT_TRUE (conv) << mode;

    std::vector<guint8> bytes
        = build_serialized_message (mode, 0, 30, 1, _NNS_TENSOR_FORMAT_STATIC, {});
    ASSERT_FALSE (bytes.empty ()) << mode;

    GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
    GstTensorsConfig config;

    gst_tensors_config_init (&config);

    GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
    EXPECT_TRUE (out_buf == NULL) << mode;

    if (out_buf)
      gst_buffer_unref (out_buf);
    gst_tensors_config_free (&config);
    gst_buffer_unref (in_buf);
  }
}

/**
 * @brief Negative: a flexible-format tensor whose carried bytes are shorter than the meta header.
 */
TEST (testConverterSerialized, flexibleHeaderTooShort_n)
{
  for (const auto &mode : available_modes ()) {
    const NNStreamerExternalConverter *conv = nnstreamer_converter_find (mode.c_str ());
    ASSERT_TRUE (conv) << mode;

    TestTensor t;
    t.name = "t";
    t.type = _NNS_UINT8;
    t.dimension = std::vector<guint32> (NNS_TENSOR_RANK_LIMIT, 1);
    t.data = std::vector<guint8> (meta_header_size () - 1, 0);

    std::vector<guint8> bytes = build_serialized_message (
        mode, 1, 30, 1, _NNS_TENSOR_FORMAT_FLEXIBLE, { t });
    ASSERT_FALSE (bytes.empty ()) << mode;

    GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
    GstTensorsConfig config;

    gst_tensors_config_init (&config);

    GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
    EXPECT_TRUE (out_buf == NULL) << mode;

    if (out_buf)
      gst_buffer_unref (out_buf);
    gst_tensors_config_free (&config);
    gst_buffer_unref (in_buf);
  }
}

/**
 * @brief Negative: a flexible-format tensor with a valid header whose declared
 * data size exceeds the bytes actually carried.
 */
TEST (testConverterSerialized, flexibleDataShorterThanDeclared_n)
{
  for (const auto &mode : available_modes ()) {
    const NNStreamerExternalConverter *conv = nnstreamer_converter_find (mode.c_str ());
    ASSERT_TRUE (conv) << mode;

    std::vector<guint8> full
        = build_flexible_bytes (_NNS_UINT8, "4:1:1:1", { 1, 2, 3, 4 });
    ASSERT_GT (full.size (), 1U) << mode;

    TestTensor t;
    t.name = "t";
    t.type = _NNS_UINT8;
    t.dimension = std::vector<guint32> (NNS_TENSOR_RANK_LIMIT, 1);
    /* Keep the header (which declares 4 bytes of data) but drop the last data byte. */
    t.data = std::vector<guint8> (full.begin (), full.end () - 1);

    std::vector<guint8> bytes = build_serialized_message (
        mode, 1, 30, 1, _NNS_TENSOR_FORMAT_FLEXIBLE, { t });
    ASSERT_FALSE (bytes.empty ()) << mode;

    GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
    GstTensorsConfig config;

    gst_tensors_config_init (&config);

    GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
    EXPECT_TRUE (out_buf == NULL) << mode;

    if (out_buf)
      gst_buffer_unref (out_buf);
    gst_tensors_config_free (&config);
    gst_buffer_unref (in_buf);
  }
}

/**
 * @brief Negative: bytes that are not a valid message of the expected format at all.
 */
TEST (testConverterSerialized, garbageBytes_n)
{
  guint8 garbage[64];

  memset (garbage, 0xff, sizeof (garbage));

  for (const auto &mode : available_modes ()) {
    if (!mode_verifies_untrusted_bytes (mode))
      continue;

    const NNStreamerExternalConverter *conv = nnstreamer_converter_find (mode.c_str ());
    ASSERT_TRUE (conv) << mode;

    GstBuffer *in_buf = wrap_as_gst_buffer (garbage, sizeof (garbage));
    GstTensorsConfig config;

    gst_tensors_config_init (&config);

    GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
    EXPECT_TRUE (out_buf == NULL) << mode;

    if (out_buf)
      gst_buffer_unref (out_buf);
    gst_tensors_config_free (&config);
    gst_buffer_unref (in_buf);
  }
}

/**
 * @brief Negative: a valid message truncated in half.
 */
TEST (testConverterSerialized, truncatedMessage_n)
{
  for (const auto &mode : available_modes ()) {
    TestTensor t = make_tensor ("t", _NNS_UINT8, 8, std::vector<guint8> ());
    for (guint8 i = 0; i < 8; i++)
      t.data.push_back (i);

    std::vector<guint8> bytes
        = build_serialized_message (mode, 1, 30, 1, _NNS_TENSOR_FORMAT_STATIC, { t });
    ASSERT_GT (bytes.size (), 1U) << mode;

    if (!mode_verifies_untrusted_bytes (mode))
      continue;

    std::vector<guint8> truncated (bytes.begin (), bytes.begin () + bytes.size () / 2);
    const NNStreamerExternalConverter *conv = nnstreamer_converter_find (mode.c_str ());
    ASSERT_TRUE (conv) << mode;

    GstBuffer *in_buf = wrap_as_gst_buffer (truncated.data (), truncated.size ());
    GstTensorsConfig config;

    gst_tensors_config_init (&config);

    GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
    EXPECT_TRUE (out_buf == NULL) << mode;

    if (out_buf)
      gst_buffer_unref (out_buf);
    gst_tensors_config_free (&config);
    gst_buffer_unref (in_buf);
  }
}

/**
 * @brief Positive: pushing a valid message through a harnessed tensor_converter yields one buffer.
 */
TEST (testConverterSerialized, harnessValidPush)
{
  for (const auto &mode : available_modes ()) {
    GstHarness *h = gst_harness_new ("tensor_converter");

    ASSERT_TRUE (h != NULL) << mode;
    gst_harness_set_src_caps_str (h, mode_caps (mode));

    TestTensor t = make_tensor ("t", _NNS_UINT8, 4, std::vector<guint8> ());
    for (guint8 i = 0; i < 4; i++)
      t.data.push_back (i);

    std::vector<guint8> bytes
        = build_serialized_message (mode, 1, 30, 1, _NNS_TENSOR_FORMAT_STATIC, { t });
    ASSERT_FALSE (bytes.empty ()) << mode;

    GstBuffer *in_buf = gst_harness_create_buffer (h, bytes.size ());
    ASSERT_EQ (gst_buffer_fill (in_buf, 0, bytes.data (), bytes.size ()), bytes.size ())
        << mode;

    EXPECT_EQ (gst_harness_push (h, in_buf), GST_FLOW_OK) << mode;

    GstBuffer *out_buf = gst_harness_try_pull (h);
    EXPECT_TRUE (out_buf != NULL) << mode;
    if (out_buf)
      gst_buffer_unref (out_buf);

    gst_harness_teardown (h);
  }
}

/**
 * @brief Negative: pushing a malformed message through a harnessed tensor_converter errors out.
 */
TEST (testConverterSerialized, harnessInvalidPush_n)
{
  guint8 garbage[64];

  memset (garbage, 0xff, sizeof (garbage));

  for (const auto &mode : available_modes ()) {
    if (!mode_verifies_untrusted_bytes (mode))
      continue;

    GstHarness *h = gst_harness_new ("tensor_converter");

    ASSERT_TRUE (h != NULL) << mode;
    gst_harness_set_src_caps_str (h, mode_caps (mode));

    GstBuffer *in_buf = gst_harness_create_buffer (h, sizeof (garbage));
    ASSERT_EQ (gst_buffer_fill (in_buf, 0, garbage, sizeof (garbage)), sizeof (garbage))
        << mode;

    EXPECT_EQ (gst_harness_push (h, in_buf), GST_FLOW_ERROR) << mode;

    gst_harness_teardown (h);
  }
}

#ifdef ENABLE_FLATBUF
/**
 * @brief Negative: flatbuf num_tensor exceeds NNS_TENSOR_SIZE_LIMIT while the message carries that many tensors.
 */
TEST (testConverterSerialized, flatbufTooManyTensors_n)
{
  const NNStreamerExternalConverter *conv = nnstreamer_converter_find ("flatbuf");
  ASSERT_TRUE (conv);

  std::vector<TestTensor> tensors (
      NNS_TENSOR_SIZE_LIMIT + 1, make_tensor ("t", _NNS_UINT8, 1, { 1 }));
  std::vector<guint8> bytes = build_flatbuf (NNS_TENSOR_SIZE_LIMIT + 1, TRUE,
      TRUE, 30, 1, _NNS_TENSOR_FORMAT_STATIC, tensors);

  GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
  GstTensorsConfig config;

  gst_tensors_config_init (&config);

  GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
  EXPECT_TRUE (out_buf == NULL);

  if (out_buf)
    gst_buffer_unref (out_buf);
  gst_tensors_config_free (&config);
  gst_buffer_unref (in_buf);
}

/**
 * @brief Negative: flatbuf num_tensor is negative, which wraps to a huge value
 * once compared as guint.
 */
TEST (testConverterSerialized, flatbufNegativeNumTensor_n)
{
  const NNStreamerExternalConverter *conv = nnstreamer_converter_find ("flatbuf");
  ASSERT_TRUE (conv);

  std::vector<guint8> bytes
      = build_flatbuf (-1, TRUE, TRUE, 30, 1, _NNS_TENSOR_FORMAT_STATIC, {});

  GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
  GstTensorsConfig config;

  gst_tensors_config_init (&config);

  GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
  EXPECT_TRUE (out_buf == NULL);

  if (out_buf)
    gst_buffer_unref (out_buf);
  gst_tensors_config_free (&config);
  gst_buffer_unref (in_buf);
}

/**
 * @brief Negative: flatbuf num_tensor is 3 but the tensor vector carries only 2 entries.
 */
TEST (testConverterSerialized, flatbufDeclaredMoreThanVector_n)
{
  const NNStreamerExternalConverter *conv = nnstreamer_converter_find ("flatbuf");
  ASSERT_TRUE (conv);

  TestTensor t0 = make_tensor ("t0", _NNS_UINT8, 1, { 1 });
  TestTensor t1 = make_tensor ("t1", _NNS_UINT8, 1, { 2 });

  std::vector<guint8> bytes
      = build_flatbuf (3, TRUE, TRUE, 30, 1, _NNS_TENSOR_FORMAT_STATIC, { t0, t1 });

  GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
  GstTensorsConfig config;

  gst_tensors_config_init (&config);

  GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
  EXPECT_TRUE (out_buf == NULL);

  if (out_buf)
    gst_buffer_unref (out_buf);
  gst_tensors_config_free (&config);
  gst_buffer_unref (in_buf);
}

/**
 * @brief Negative: flatbuf message with no `fr` field.
 */
TEST (testConverterSerialized, flatbufMissingFrameRate_n)
{
  const NNStreamerExternalConverter *conv = nnstreamer_converter_find ("flatbuf");
  ASSERT_TRUE (conv);

  TestTensor t = make_tensor ("t", _NNS_UINT8, 1, { 1 });

  std::vector<guint8> bytes
      = build_flatbuf (1, FALSE, TRUE, 30, 1, _NNS_TENSOR_FORMAT_STATIC, { t });

  GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
  GstTensorsConfig config;

  gst_tensors_config_init (&config);

  GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
  EXPECT_TRUE (out_buf == NULL);

  if (out_buf)
    gst_buffer_unref (out_buf);
  gst_tensors_config_free (&config);
  gst_buffer_unref (in_buf);
}

/**
 * @brief Negative: flatbuf message with no `tensor` field.
 */
TEST (testConverterSerialized, flatbufMissingTensorVector_n)
{
  const NNStreamerExternalConverter *conv = nnstreamer_converter_find ("flatbuf");
  ASSERT_TRUE (conv);

  std::vector<guint8> bytes
      = build_flatbuf (1, TRUE, FALSE, 30, 1, _NNS_TENSOR_FORMAT_STATIC, {});

  GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
  GstTensorsConfig config;

  gst_tensors_config_init (&config);

  GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
  EXPECT_TRUE (out_buf == NULL);

  if (out_buf)
    gst_buffer_unref (out_buf);
  gst_tensors_config_free (&config);
  gst_buffer_unref (in_buf);
}

/**
 * @brief Negative: a flatbuf tensor with no `data` field.
 */
TEST (testConverterSerialized, flatbufTensorMissingData_n)
{
  const NNStreamerExternalConverter *conv = nnstreamer_converter_find ("flatbuf");
  ASSERT_TRUE (conv);

  TestTensor t = make_tensor ("t", _NNS_UINT8, 1, {});
  t.has_data = FALSE;

  std::vector<guint8> bytes
      = build_flatbuf (1, TRUE, TRUE, 30, 1, _NNS_TENSOR_FORMAT_STATIC, { t });

  GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
  GstTensorsConfig config;

  gst_tensors_config_init (&config);

  GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
  EXPECT_TRUE (out_buf == NULL);

  if (out_buf)
    gst_buffer_unref (out_buf);
  gst_tensors_config_free (&config);
  gst_buffer_unref (in_buf);
}

/**
 * @brief Positive: a flatbuf tensor with no `name` field converts with a NULL name.
 */
TEST (testConverterSerialized, flatbufNoNameField)
{
  const NNStreamerExternalConverter *conv = nnstreamer_converter_find ("flatbuf");
  ASSERT_TRUE (conv);

  TestTensor t = make_tensor (nullptr, _NNS_UINT8, 4, { 1, 2, 3, 4 });

  std::vector<guint8> bytes
      = build_flatbuf (1, TRUE, TRUE, 30, 1, _NNS_TENSOR_FORMAT_STATIC, { t });

  GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
  GstTensorsConfig config;

  gst_tensors_config_init (&config);

  GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
  ASSERT_TRUE (out_buf != NULL);
  EXPECT_TRUE (config.info.info[0].name == NULL);

  gst_buffer_unref (out_buf);
  gst_tensors_config_free (&config);
  gst_buffer_unref (in_buf);
}

/**
 * @brief Positive: a flatbuf `dimension` vector shorter than
 * NNS_TENSOR_RANK_LIMIT converts, with the missing ranks read as 0.
 */
TEST (testConverterSerialized, flatbufShortDimensionVector)
{
  const NNStreamerExternalConverter *conv = nnstreamer_converter_find ("flatbuf");
  ASSERT_TRUE (conv);

  TestTensor t;
  t.name = "t";
  t.type = _NNS_UINT8;
  t.dimension = { 5, 4, 3, 2 }; /* only 4 of the 16 ranks */
  t.data = std::vector<guint8> (5 * 4 * 3 * 2, 7);

  std::vector<guint8> bytes
      = build_flatbuf (1, TRUE, TRUE, 30, 1, _NNS_TENSOR_FORMAT_STATIC, { t });

  GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
  GstTensorsConfig config;

  gst_tensors_config_init (&config);

  GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
  ASSERT_TRUE (out_buf != NULL);

  EXPECT_EQ (config.info.info[0].dimension[0], 5U);
  EXPECT_EQ (config.info.info[0].dimension[1], 4U);
  EXPECT_EQ (config.info.info[0].dimension[2], 3U);
  EXPECT_EQ (config.info.info[0].dimension[3], 2U);
  for (guint j = 4; j < NNS_TENSOR_RANK_LIMIT; j++)
    EXPECT_EQ (config.info.info[0].dimension[j], 0U) << j;

  gst_buffer_unref (out_buf);
  gst_tensors_config_free (&config);
  gst_buffer_unref (in_buf);
}

/**
 * @brief Negative: flexbuf message missing the `tensor_1` key while `num_tensors` says 2.
 */
TEST (testConverterSerialized, flexbufMissingTensorKey_n)
{
  const NNStreamerExternalConverter *conv = nnstreamer_converter_find ("flexbuf");
  ASSERT_TRUE (conv);

  TestTensor t0 = make_tensor ("t0", _NNS_UINT8, 1, { 1 });
  TestTensor t1 = make_tensor ("t1", _NNS_UINT8, 1, { 2 });

  /* the last argument leaves out the tensor_1 key */
  std::vector<guint8> bytes
      = build_flexbuf (2, 30, 1, _NNS_TENSOR_FORMAT_STATIC, { t0, t1 }, 1);

  GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
  GstTensorsConfig config;

  gst_tensors_config_init (&config);

  GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
  EXPECT_TRUE (out_buf == NULL);

  if (out_buf)
    gst_buffer_unref (out_buf);
  gst_tensors_config_free (&config);
  gst_buffer_unref (in_buf);
}

/**
 * @brief Negative: flexbuf `tensor_0[3]` (the data field) is an Int rather than a Blob.
 */
TEST (testConverterSerialized, flexbufDataFieldNotBlob_n)
{
  const NNStreamerExternalConverter *conv = nnstreamer_converter_find ("flexbuf");
  ASSERT_TRUE (conv);

  TestTensor t = make_tensor ("t", _NNS_UINT8, 1, { 1 });
  t.data_is_blob = FALSE;

  std::vector<guint8> bytes = build_flexbuf (1, 30, 1, _NNS_TENSOR_FORMAT_STATIC, { t });

  GstBuffer *in_buf = wrap_as_gst_buffer (bytes.data (), bytes.size ());
  GstTensorsConfig config;

  gst_tensors_config_init (&config);

  GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
  EXPECT_TRUE (out_buf == NULL);

  if (out_buf)
    gst_buffer_unref (out_buf);
  gst_tensors_config_free (&config);
  gst_buffer_unref (in_buf);
}
#endif /* ENABLE_FLATBUF */

#ifdef ENABLE_PROTOBUF
/**
 * @brief Negative: protobuf num_tensor exceeds NNS_TENSOR_SIZE_LIMIT while the message carries that many tensors.
 */
TEST (testConverterSerialized, protobufTooManyTensors_n)
{
  const NNStreamerExternalConverter *conv = nnstreamer_converter_find ("protobuf");
  ASSERT_TRUE (conv);

  std::vector<TestTensor> tensors (
      NNS_TENSOR_SIZE_LIMIT + 1, make_tensor ("t", _NNS_UINT8, 1, { 1 }));
  std::string s = build_protobuf (
      NNS_TENSOR_SIZE_LIMIT + 1, 30, 1, _NNS_TENSOR_FORMAT_STATIC, tensors);

  GstBuffer *in_buf = wrap_as_gst_buffer (s.data (), s.size ());
  GstTensorsConfig config;

  gst_tensors_config_init (&config);

  GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
  EXPECT_TRUE (out_buf == NULL);

  if (out_buf)
    gst_buffer_unref (out_buf);
  gst_tensors_config_free (&config);
  gst_buffer_unref (in_buf);
}

/**
 * @brief Negative: protobuf num_tensor is 3 but only 2 Tensor entries are carried.
 */
TEST (testConverterSerialized, protobufDeclaredMoreThanVector_n)
{
  const NNStreamerExternalConverter *conv = nnstreamer_converter_find ("protobuf");
  ASSERT_TRUE (conv);

  TestTensor t0 = make_tensor ("t0", _NNS_UINT8, 1, { 1 });
  TestTensor t1 = make_tensor ("t1", _NNS_UINT8, 1, { 2 });

  std::string s = build_protobuf (3, 30, 1, _NNS_TENSOR_FORMAT_STATIC, { t0, t1 });

  GstBuffer *in_buf = wrap_as_gst_buffer (s.data (), s.size ());
  GstTensorsConfig config;

  gst_tensors_config_init (&config);

  GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
  EXPECT_TRUE (out_buf == NULL);

  if (out_buf)
    gst_buffer_unref (out_buf);
  gst_tensors_config_free (&config);
  gst_buffer_unref (in_buf);
}

/**
 * @brief Positive: a protobuf tensor with only 4 `dimension` entries converts,
 * with the missing ranks read as 0.
 */
TEST (testConverterSerialized, protobufShortDimensionField)
{
  const NNStreamerExternalConverter *conv = nnstreamer_converter_find ("protobuf");
  ASSERT_TRUE (conv);

  TestTensor t;
  t.name = "t";
  t.type = _NNS_UINT8;
  t.dimension = { 5, 4, 3, 2 }; /* only 4 of the 16 ranks */
  t.data = std::vector<guint8> (5 * 4 * 3 * 2, 7);

  std::string s = build_protobuf (1, 30, 1, _NNS_TENSOR_FORMAT_STATIC, { t });

  GstBuffer *in_buf = wrap_as_gst_buffer (s.data (), s.size ());
  GstTensorsConfig config;

  gst_tensors_config_init (&config);

  GstBuffer *out_buf = conv->convert (in_buf, &config, NULL);
  ASSERT_TRUE (out_buf != NULL);

  EXPECT_EQ (config.info.info[0].dimension[0], 5U);
  EXPECT_EQ (config.info.info[0].dimension[1], 4U);
  EXPECT_EQ (config.info.info[0].dimension[2], 3U);
  EXPECT_EQ (config.info.info[0].dimension[3], 2U);
  for (guint j = 4; j < NNS_TENSOR_RANK_LIMIT; j++)
    EXPECT_EQ (config.info.info[0].dimension[j], 0U) << j;

  gst_buffer_unref (out_buf);
  gst_tensors_config_free (&config);
  gst_buffer_unref (in_buf);
}
#endif /* ENABLE_PROTOBUF */

/**
 * @brief Main gtest entry point.
 */
int
main (int argc, char **argv)
{
  int result = -1;

  testing::InitGoogleTest (&argc, argv);

  gst_init (&argc, &argv);

  try {
    result = RUN_ALL_TESTS ();
  } catch (...) {
    g_warning ("catch `testing::internal::<unnamed>::ClassUniqueToAlwaysTrue'");
  }

  return result;
}
