[files]
extend-exclude = ["tests/test_models/models/*", "tests/test_models/labels/*", "tests/test_models/data/*", "tests/nnstreamer_decoder_boundingbox/*"]

[default.extend-words]
mosquitto = "mosquitto"
iy = "iy"
addd = "addd"
ND = "ND"
thr = "thr"
wth = "wth"
ot = "ot"
GES = "GES" # GStreamer plugin definition (GSTREAMER_PLUGINS_GES) for Android build
Seeked = "Seeked"
ba = "ba"
splitted = "splitted"
