name: Docker Tizen App Build Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v1
    - name: prepare deb sources for GBS
      run: echo "deb [trusted=yes] http://download.tizen.org/tools/latest-release/Ubuntu_18.04/ /" | sudo tee /etc/apt/sources.list.d/tizen.list
    - name: install GBS
      run: sudo apt-get update && sudo apt-get install -y gbs
    - name: configure GBS
      run: cp .github/workflows/tizen.gbs.conf ~/.gbs.conf
    - name: make cache key
      id: make-key
      run: echo "cache_key=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      shell: bash
    - name: cache gbs cache
      id: cache-gbs-root
      uses: actions/cache@v3
      with:
        path: ~/GBS-ROOT/local/cache
        key: ${{ steps.make-key.outputs.cache_key }}
    - name: Tizen studio docker build
      run: pushd tools/docker/TizenAppBuild && docker build
