name: Build test / Yocto-5.0.3 (scarthgap-5.0.3)

on:
  pull_request:
    branches: [ main ]

  # Allow manually triggering the workflow
  workflow_dispatch:

jobs:
  build:
    name: Build with Yocto / meta-neural-network on Ubuntu
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: -${{ github.event.pull_request.commits }}
    - name: Check if rebuild required
      uses: ./.github/actions/check-rebuild
      with:
        mode: build

    - name: make cache dir for yocto
      ## prevent permission error
      run: sudo mkdir --mode a=rwx --parents /var/cache/yocto

    - name: restore yocto sstate and downloads cache
      if: github.ref == 'refs/heads/main' || env.rebuild == '1'
      uses: actions/cache/restore@v4
      with:
        path: |
          /var/cache/yocto/downloads
          /var/cache/yocto/sstate-cache
          /var/cache/yocto/persistent
        key: yocto-cache-yocto-5.0.3
    - name: build
      if: github.ref == 'refs/heads/main' || env.rebuild == '1'
      run: |
        echo "::group::apt-get install"
        sudo apt-get update
        sudo apt install gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 python3-subunit zstd liblz4-tool file locales libacl1
        pip install websockets
        sudo locale-gen en_US.UTF-8
        echo "::endgroup::"

        echo "::group::Prepare poky and meta-neural-network"
        git clone git://git.yoctoproject.org/poky -b yocto-5.0.3 && cd poky
        git clone https://github.com/nnstreamer/meta-neural-network -b scarthgap
        echo 'SRC_URI = "git://${{ github.workspace }}/;protocol=file;usehead=1;nobranch=1"' >> meta-neural-network/recipes-nnstreamer/nnstreamer/nnstreamer_%.bbappend
        source oe-init-build-env
        bitbake-layers add-layer ../meta-neural-network
        echo "::endgroup::"

        echo "::group::Set local.conf"
        echo 'DL_DIR = "/var/cache/yocto/downloads"' >> conf/local.conf
        echo 'BB_GENERATE_MIRROR_TARBALLS = "1"' >> conf/local.conf
        echo 'SSTATE_DIR = "/var/cache/yocto/sstate-cache"' >> conf/local.conf
        echo 'BB_SIGNATURE_HANDLER = "OEEquivHash"' >> conf/local.conf
        echo 'BB_HASHSERVE = "auto"' >> conf/local.conf
        echo 'BB_HASHSERVE_UPSTREAM = "wss://hashserv.yoctoproject.org/ws"' >> conf/local.conf
        echo 'SSTATE_MIRRORS ?= "file://.* http://cdn.jsdelivr.net/yocto/sstate/all/PATH;downloadfilename=PATH"' >> conf/local.conf
        echo 'PERSISTENT_DIR="/var/cache/yocto/persistent"' >> conf/local.conf
        echo "::endgroup::"

        echo "::group::Do setscene-only task and disregard its error"
        bitbake --setscene-only nnstreamer || true
        echo "::endgroup::"

        echo "::group::Build nnstreamer"
        bitbake --skip-setscene nnstreamer
        echo "::endgroup::"

        echo "::group::Cat build log"
        cat tmp/work/core2-64-poky-linux/nnstreamer/*/temp/log.do_configure || true
        cat tmp/work/core2-64-poky-linux/nnstreamer/*/temp/log.do_compile || true
        echo "::endgroup::"

        sudo rm -rf tmp/
    - name: save yocto cache (main branch only)
      uses: actions/cache/save@v4
      if: always() && github.ref == 'refs/heads/main'
      with:
        path: |
          /var/cache/yocto/downloads
          /var/cache/yocto/sstate-cache
          /var/cache/yocto/persistent
        key: yocto-cache-yocto-5.0.3
